### ISSUE TITLE
GUI Display Issues

### ISSUE THREAD

**Issue by Guybrush0** [p455w0rd/DankNull#10]
Version: 1.12-1.0.6

GUI issues with display of items, there is actually a few thousand cobble and assorted other items but shows this, with blank spaces and such

https://i.imgur.com/DaaumHb.png

**Comment by p455w0rd** [comment]
I noticed this last night. This may be a bug with the number converter. I'm guessing there is probably 39K or something like that. Working on it. Thanks for the report!

**Comment by p455w0rd** [comment]
So this is now fixed, and I added a count to the tooltip for items over 1k :)
![](http://p455w0rd.net/u/09.18.59-08.10.17.gif)
