### ISSUE TITLE
Shift-left clicking with dank/null on a garden from Pam's Harvestcraft 'silk touches' the garden

### ISSUE THREAD

**Issue by dmsaxon** [p455w0rd/DankNull#100]
As per the description - on the DW 1.12 pack (v1.10) if I shift+left-click on a garden (tried two or three types), it generates a garden item that I can pick up and place.

Shift+left-click doesn't silk touch other things such as normal grass.

**Comment by scotty9090** [comment]
That's intended behavior from Pam's.  You can shift-left click with an open hand (or anything else i believe) to pick up a garden without breaking it.
