### ISSUE TITLE
not working in multiplayer

### ISSUE THREAD

**Issue by yellow42069** [p455w0rd/DankNull#102]
Im playing with my friends on direwolf 20 modpack 1.12.2 and dank null recipies/models are not showing up, i have tried to make them but nothing works, please help :)

**Comment by ProsperCraft** [comment]
FYI, not having this problem on my 1.12.2 modpack.

**Comment by evildub** [comment]
Also having this happen on Revelations 1.8 Cant find anything showing it to be disabled.

**Comment by p455w0rd** [comment]
this appears to be on FTB's end for whatever reason..could be outdated mod, could be erroneous CT scripts..the fact that this doesn't happen for me using other packs (including completely custom packs), tells me that things are good on my end...today is my birthday, so no coding today, but I'll be getting this update out immediately following the Minechem 1.12.2 Alpha release
