### ISSUE TITLE
Client Crash - p455w0rd.danknull.client.render.DankNullRenderer.renderItem

### ISSUE THREAD

**Issue by ProsperCraft** [p455w0rd/DankNull#104]
https://pastebin.com/ZxnDNNTt

**Comment by rbandboy** [comment]
[latest.log](https://github.com/p455w0rd/DankNull/files/1882665/latest.log)
Full file was too big to pastebin.

**Comment by rbandboy** [comment]
Culprit was likely a Mark IV, although the player file has listed two Mark III's side by side.
Listed item was torches, and may have ran out of the listed item.

**Comment by rbandboy** [comment]
https://pastebin.com/DHxi7aqZ
Updated java and video card crashlogs.

**Comment by ProsperCraft** [comment]
I did /invsee on his inventory to see if I could remove it from his inventory and - 
https://gist.github.com/ProsperCraft/4c37f992e5a70fc4320a5663ae5b2e3b

**Comment by p455w0rd** [comment]
@ProsperCraft any chance I can talk with you on discord?

**Comment by ProsperCraft** [comment]
Of course, here is my discord - https://discord.gg/0YcHRlg0xIojCvGu

**Comment by VulkanX** [comment]
I'm getting this error in the Revelation FTB pack was there a resolution to this issue?

**Comment by p455w0rd** [comment]
@VulkanX if you want to hop on my discord, I can send you a private build to test https://discord.gg/9J7yhUP
