### ISSUE TITLE
dank/null not working

### ISSUE THREAD

**Issue by Aromix** [p455w0rd/DankNull#107]
I recently tried using the dank/null but there is alot of issues for me.
First of all im playing FTB direwolf20 1.12 with no extra mods or plugins.
Second of all lets get to the problems
1. Even if i have put say 64 cobble in the dank/null then when i pick up more cobble of the ground it just appears in my inventory instead of in the dank/null 
2. if i try to change the selected block when holding the dank/null it deletes everything in the dank null

I hope someone has an answer for this, it looked like a really cool mod

**Comment by Aromix** [comment]
Also if i put something in it and acces a inventory like my ME system it resets the dank/null and puts all the items in it back in my inventory

**Comment by TudorNan** [comment]
I'm having the same issue. How did you manage to fix it?(if you did)

**Comment by AnotherDoctor** [comment]
Yeah I am also having this problem and I really wanna play with the mod, it's so useful.

**Comment by Aromix** [comment]
I didn’t find any solution on the internet so I posted here fore an answer.
I also stopped playing the pack that had the /dank/null in it a couple weeks ago.

**Comment by Aromix** [comment]
Also I get no answers for a whole month and then I get 2 in the same 24 hours.

**Comment by p455w0rd** [comment]
i released an update yesterday, let me know if this is still an issue with that version

**Comment by Aromix** [comment]
Hello! Great that you fixed it. But... you were a little late. I stopped playing shortly after making this thread.
