### ISSUE TITLE
dank/null + AE2 pipes = crash

### ISSUE THREAD

**Issue by destrucktoid** [p455w0rd/DankNull#113]

**Comment by destrucktoid** [comment]
basically whenever the game loads up i join and i recieve this crash:
Error: java.lang.NullPointerException: Rendering item
i checked the folders and believe it to be caused by this:
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at p455w0rd.danknull.client.render.DankNullRenderer.renderItem(DankNullRenderer.java:107)

**Comment by destrucktoid** [comment]
if you want i can leave the entire crash report

**Comment by p455w0rd** [comment]
/dank/null version?

**Comment by destrucktoid** [comment]
DankNull-1.12-1.4.33
i managed to (because it is a server) get someone to setup a perpetual killing machine with /kill that killed me before i rendered in which sorted the problem of me crashing, but once i broke my grave - Error: java.lang.NullPointerException: Rendering item in world

**Comment by p455w0rd** [comment]
thx..i already have this fixed in dev..just gotta get this update out
