### ISSUE TITLE
[Feature Request] Item sorting/locking

### ISSUE THREAD

**Issue by BonaireDreams** [p455w0rd/DankNull#115]
It would be really nice if item types could be locked in position or have it always keep 1 of an item type. When using the dank null to build I like to keep Cobble, dirt and stone together. Until I accidentally place the last piece of dirt. When I refill dirt its now four or 6 or whatever slots away so I no longer just scroll once to get to it. If we could lock item type to their slot so the last piece never gets placed it would easier to keep often used type together.

**Comment by p455w0rd** [comment]
i've had this request enough times..i see what I can do when I next work on /dank/null

**Comment by p455w0rd** [comment]
https://puu.sh/AzAqm/cc28583866.webm :)

**Comment by BonaireDreams** [comment]
O.O   🎉

**Comment by Jaeiya** [comment]
I'd just like to add to this, that sometimes I want an item in a different spot, so I can scroll to it quicker... Be nice to be able to swap slots.

**Comment by Hund** [comment]
@p455w0rd: Is that supposed to keep the last one in the /dank/null? It doesn't for me, I can still place the last one in the world.
