### ISSUE TITLE
Dank Null as an inventory for quarries - Feature Request

### ISSUE THREAD

**Issue by smilodon79** [p455w0rd/DankNull#118]
I know that items can be pulled out of the dank null using the dank null base thingy.  But would it be possible to make the dank null emulate an inventory for piping items into it, so that we can just plop it on top of a quarry and call it a day?  The Emerald version especially would be fantastic if it can support that feature.  As things stand, the chest above the quarry calls for a laggy contraption (ender chest or crates with piping out, etc.)

**Comment by KollinsPlays** [comment]
I second this request. I can think of many ways to use a docked dank/null to store items and then void the rest. Possibly a more advanced station that is a full block so pipes can be attached to more than one side that can both put items into and pull items from a docked dank/null.

**Comment by p455w0rd** [comment]
i've had enough requests..I will be implementing this...it will be a config option that will need to be enable for this functionality though

**Comment by VariableVixen** [comment]
Ah, question for you p455w0rd - I just grabbed the latest release off CurseForge, which is (as of typing this) 14 hours old. Looking in the config file (because I really wanted this feature myself) I can't find anything about inserting items in the dock. Has this not made it into the release yet?

**Comment by p455w0rd** [comment]
@PrincessRTFM  i forgot to add a config lol..it should just work..lmk if it doesnt

**Comment by VariableVixen** [comment]
It works, although only the selected item/block seems to allow insertion. Is that intended behaviour, or should I open a bug report? (I feel like it'd be more useful if you could insert anything it already holds, but I also know that might be a little overpowered to some people... I'd personally prefer it, but you're the dev!)

**Comment by BrockWS** [comment]
Seems to be working. The code doesn't care about the selected slot.
![image](https://user-images.githubusercontent.com/2309747/64488232-ee7c0080-d288-11e9-81b5-71f65d51295c.png)

**Comment by VariableVixen** [comment]
Maybe I was doing something wrong, then... I'll try a basic setup and see if that was it.

**Comment by Nicklas185105** [comment]
Does this not work anymore in 1.12.2?
Can't find anything in the config file either
