### ISSUE TITLE
Concurrent modification crash on client world load

### ISSUE THREAD

**Issue by Darkmega18** [p455w0rd/DankNull#121]
[crash-2018-06-20_20.20.41-client.txt](https://github.com/p455w0rd/DankNull/files/2118864/crash-2018-06-20_20.20.41-client.txt)

got hit with this when loading up my world. don't know where it came from but it makes reference to your stuff only as far as I can tell, and only thing of yours I have is this and p455w0rd lib to make it run. I had recently updated these mods in my pack and it hadn't done this until this evening when I came through and did a set of updates for some mods.

Starting up my world for a quick test drive was when it blew up. Although it didn't happen again when I loaded it a second time. I figured I'd report it as one of those "weird" errors so to let you know as it might come back.

**Comment by p455w0rd** [comment]
sooo weird...i can tell you with pretty good certainty, that it's not me lol this is referencing an `ArrayList` being altered more than once before an iteration of a `for loop` has finished..(there is no ArrayList...or list of any sort in the method being referenced)...the fix would be simple if it were this thankfully..still thank you for the heads up..good to have record of stuff like this

**Comment by p455w0rd** [comment]
oh..to be clear..what I mean by 'not me'..is..this is a one-off...could be MC, Forge, hardware..who knows

**Comment by Darkmega18** [comment]
Roger. yeah, it was a one off so far. hasn't happened since reloading a couple more times. I never even had a dank on me at the time. so it was a weird one. :V
