### ISSUE TITLE
Shift + Right Click Not opening danknull gui

### ISSUE THREAD

**Issue by Hyperion505** [p455w0rd/DankNull#122]
As stated above i cant open the gui with shift right click. If i set the keybind for "open nearest dank null" from the default, none, to anything else, I cant use the dank null as it wont hold items or pickup items or allow me to add items to its gui.

**Comment by CharCharthemonkey** [comment]
ive had a similar issue with not being able to open the dank null best way ive found to "work around" it was to drop it on the ground pick it back up then it opens

**Comment by KollinsPlays** [comment]
I've also had them randomly unable to SHIFT+RIGHT CLICK to open. It seems very random and usually goes away after some time on it's own.

**Comment by SHsuperCM** [comment]
Can confirm, happening to me too.. Really breaks the usability of the mod..

**Comment by p455w0rd** [comment]
ok..so there are certain situations where opening the GUI will not work..like if you're on the edge of a block..this is to protect you in situations like where you might be building a bridge across lava in the nether..to prevent you from falling to your death cuz the GUI opens when u don't want it to...
I'll be doing a /dank/null dev stream on twitch today...so join my discord and be watching my twitter for when I go live if you want to see how my local version is compared to your version..I have implemented a ton of fixes and it's finally time for me to work on it again..hope to see you all around! http://p455w0rd.net/twitch - http://p455w0rd.net/discord

**Comment by p455w0rd** [comment]
should be fixed for most situations (still will not open if you're on the edge of a block)...I could add a client config to ignore the checks i do for this..if you want that, open another issue and i'll mark it as a feature request and implement it..thanks for reporting
