### ISSUE TITLE
[Cross-Mod Issue] Thaumcraft 6 Vis Crystals change to single type when placed in DankNull

### ISSUE THREAD

**Issue by altoidsyn** [p455w0rd/DankNull#123]
Pack is the DireWolf20 1.12 v2.0.0

The issue occurs when vis crystals are placed or stored in the DankNull. I discovered the issue in survival and tested it in creative. The dank/null stores all Vis crystals as the first kind placed in it (So if Terra is placed in first, any vis crystals that go into the dank/null become Terra).

**Comment by p455w0rd** [comment]
same issue as #95and #105 through #111
