### ISSUE TITLE
Duplication of Astral Sorcery Constellation papers

### ISSUE THREAD

**Issue by CrypticEnigma00** [p455w0rd/DankNull#124]
Steps to reproduce.
Place a filled Constellation paper say Evorio into dank null.
Place any other Constellation paper into the Dank null (does not matter if it has another Constellation or not) .  

Result
 The second placed paper will take the constellation that is already in the Dank onto it.

Extra info 
I tested trying to give another player the Constellation paper (tested using Pelotrio part of the gated papers).  The Player I gave the paper to had not started Astral Sorcery.

Result of extra testing
The player was able to use the paper with no issues.

Expected result 
Blank Constellation papers to stack 
Marked Constellation papers to be placed into individual slots within Dank null

**Comment by p455w0rd** [comment]
nbt issue, fixed in #95
