### ISSUE TITLE
danknull with old keep inventory rule kicks all clients to login

### ISSUE THREAD

**Issue by BonaireDreams** [p455w0rd/DankNull#125]
Dank Null Version: 1.12-1.4.33

I had removed the Deep Resonance mod from our server as no one was really using it. One player had enabled "Keep 1 item" for everything in his danknull. After removing Deepresonance he would be kicked out to the login screen when he tried to open his Danknull. No hard crash, no crash report. I was watching the console window and it just gave the "Player XXX has lost connection" "XXXX has logged out" message. Even stranger if he placed the Danknull on his extractor, every single player on the server was logged out.

The Danknull worked fine otherwise, he could scroll through all the items in the DankNull and place and pick up items fine.

I opened his Player.dat in NBTEdit, found the DankNull, He had 44 entries for inventory, which we matched to him scrolling through his danknull while I looked through the entries. But he had 46 entries under the "Inventory to keep" section (Sorry wrong terminology but I'm at work and don't recall what the field is)  Looking through there he still had an entry for "Deep Resonance Ore: Keep 1"

I deleted that, shutdown server, uploaded his patched file, started server, problem resolved. 

So there is a glitch where items set to keep in danknull inventory can cause all players to be disconnected if a mod for those items is removed.

**Comment by p455w0rd** [comment]
yeah..this isn't a glitch..this is just how modded works...removing mods from world generally breaks them

**Comment by BonaireDreams** [comment]
That makes sense. I did have to /fml confirm to have the blocks removed from the world, but that of course would not know to remove the keep section for danknull. All good, just thought I'd report it in case there was a way to check for missing items and remove them. Not planning on removing many mods and its an easy fix with NBTedit :)

Thanks

**Comment by p455w0rd** [comment]
i'll talk to some friends..depending on how much of a pain it would be, i might add a check..i'm sure it can be done..just thinking about it, it sounds like a lot more work than its worth
