### ISSUE TITLE
Can't Rename Dank Nulls with Scripts

### ISSUE THREAD

**Issue by TwilightPSN** [p455w0rd/DankNull#127]
Trying to rename the Dank nulls in my pack is wont allow me to in the scripts. it doesnt give me syntax errors but wont update the name

<danknull:dank_null_panel:4>.displayName =

thats the display name i am using

**Comment by p455w0rd** [comment]
I was requested to add support for this in stream..I will mark this as a feature request and get it implemented :)

**Comment by p455w0rd** [comment]
so I'm not sure what's going on, but renaming works for me, so maybe the script is wrong or something..but they're renamable in an anvil, which means the error is not on my end..it's also possible that I just forgot that i did this code months ago lol...either it, it works now
