### ISSUE TITLE
Console spam whe used with Sponge

### ISSUE THREAD

**Issue by TheOpalium** [p455w0rd/DankNull#128]
Hello!

I'm having a small problem with /dank/null and SpongeForge. When used together, doing different actions with a /dank/null result in the following line spamming in the console:
`[14:07:02] [Server thread/INFO] [Sponge]: Container was not captured. No ClickInventoryEvent will be fired! Container: class p455w0rd.danknull.container.ContainerDankNull PacketState: PrimaryInventoryShiftClick`
It just repeats the same line over and over again, around 20 times.

While nothing technically breaks, it makes it very difficult to read the console log and using it.

I'm using Sponge 1.12.2 BETA-3341, Forge 14.23.4.2735 and /dank/null 1.4.33.

Any ideas how to solve this?

**Comment by p455w0rd** [comment]
spongeforge doesn't get along well with many mods...your options are: don't use sponge or don't use /dank/null, sorry
