### ISSUE TITLE
Crash when changing modes in /dank/null GUI

### ISSUE THREAD

**Issue by LocalBoomer** [p455w0rd/DankNull#130]
When I try to enable ore dict mode in the GUI my game crashes and disconnects me from the 'server' (am playing SP but I believe forge uses a server for single player anyway) I don't get a crash report however just crash to server select screen

[latest.log](https://github.com/p455w0rd/DankNull/files/2263157/latest.log)

If you need anything more let me know

**Comment by p455w0rd** [comment]
should be fixed in latest update..let me know if not
