### ISSUE TITLE
Client crash with 1.4.41 - IllegalAccessError: tried to access field net.minecraft.client.gui.inventory.GuiContainer.field_147005_v

### ISSUE THREAD

**Issue by ProsperCraft** [p455w0rd/DankNull#137]
I just updated to 1.4.41, started a new world, and pulled an emerald dank out using cheat mode in jei, and on first open I got this client crash.

https://gist.github.com/ProsperCraft/3e4ec2335a7ec563e18f44853ca7b8e5
Reproduced here-
https://gist.github.com/ProsperCraft/c1128cbc84916058b40454087ce89ce2

Here is the console message-
https://gist.github.com/ProsperCraft/b562d4c5f7616fcdc7d340edcd272a32

**Comment by p455w0rd** [comment]
thank you..i'll get the fix pushed to curse..I thought I checked this :/

**Comment by p455w0rd** [comment]
pushed to curse..awaiting approval
