### ISSUE TITLE
Not seeing p455word's lib 2.0.22

### ISSUE THREAD

**Issue by Zeevian** [p455w0rd/DankNull#14]
downloaded the latest updates of both, starting minecraft throws a "missing dependency" error.

CodeChickenLib-1.12-3.1.3.313-universal.jar
RedstoneFlux-1.12-2.0.1.2-universal.jar
DankNull-1.12-1.0.9.jar
p455w0rdslib-1.12-2.0.22.jar

tested with removing all mods outside of the needed ones.

**Comment by Zedrimar** [comment]
confirmed

**Comment by RedBullSlurpie** [comment]
Happening here as well.

**Comment by p455w0rd** [comment]
well did you try downloading that version of pwthings? https://minecraft.curseforge.com/projects/p455w0rds-library/files/2493634

**Comment by RedBullSlurpie** [comment]
Yes, when I launch the game it still says to get the latest (2.0.22) even though I already have it. Downgrading to the past Dank Null version, and P455W0rds Lib works fine.

**Comment by Zeevian** [comment]
yes, @p455w0rd, i made sure to include that when i started mc

**Comment by OneEyeMaker** [comment]
@p455w0rd 
The same issue only with p455w0rdlib and /Dank/Null on 1.12+

**Comment by p455w0rd** [comment]
:/ i hate maven's versioning (this is what Forge uses when specifying a specific required version dependency)..I forgot the @ ..will new builds out asap
