### ISSUE TITLE
[Multiplayer][1.12.2] Placing blocks under user causes client desync

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [p455w0rd/DankNull#142]
When on a multiplayer server with any amount of lag, placing blocks directly under one's self causes a desync where the client displays falling and the server sees the player as standing on a block. I believe this is caused by not placing blocks on both the client and the server [If this is the case, the relevant code is here](https://github.com/p455w0rd/DankNull/blob/master/src/main/java/p455w0rd/danknull/items/ItemDankNull.java#L138-L164)

Using /dank/null version 1.12-1.4.43 on the Enigmatic 2 Expert modpack

**Comment by p455w0rd** [comment]
i'll be pushing an update today...please, if you can, join my discord and confirm whether or not this is still happening..the `onItemRightClick` method code is greatly reduced in-dev and only handles opening the GUI now, so this should no longer be an issue. https://discord.gg/8g62YV7

**Comment by A-UNDERSCORE-D** [comment]
Sure, will check it out in a bit
