### ISSUE TITLE
Dank Null Duping Issue

### ISSUE THREAD

**Issue by Rithsagea** [p455w0rd/DankNull#143]
Bug:
Dank Null dupes items.

Steps to reproduce:
Place item(s) into /dank/null.
Set the extract mode to "Extract all but 1" (you have to cycle around if it is already on that mode)
Take items out.
Leave the inventory.
Open the /dank/null again.
Take out items that were originally inserted.

If my instructions were a bit vague, I've included a video to help.
https://www.youtube.com/watch?v=QutuCkqzlh8

This was done in a test world with only the following mods:

/dank/null 1.4.43
CodeChicken Lib 3.2.2.353
p455w0rdslib 2.0.35

**Comment by Rithsagea** [comment]
Note: this works on every single /dank/null.
I discovered this bug on an emerald one.

**Comment by Rithsagea** [comment]
Update: Simply changing the extraction mode seems to work. It doesn't have to be just "Extract all but 1"

**Comment by p455w0rd** [comment]
thank you for this informative report! sorry it took so long to get to it..I believe I have fixed the issue but would like to have you test it..please join my discord, DM me, and I'll send you a jar with the fixes implemented - https://p455w0rd.net/discord

**Comment by Ahzuraki** [comment]
I am using the latest DankNull-1.12-1.4.46.jar from 12 January. 
The changelog says "Fixed Dupe Bug" yet I'm still able to replicate this.
The way you do it is by putting an item in it you wish to dupe, then you close it. 
You open and Q-throw it out then close it. When you open it again the item will still be in it.
You can then rinse and repeat for infinite (put item name here).
I do not think the extract mode matters.
Imgur album with proof i'm able to dupe items, the mod pack is Project Ozone 3.

https://imgur.com/a/GUOJZvR

Separate sidenote, I also get a danknull copy from my friend in my lan world every time he adds an item to it. 
Say he has his danknull in the last slot and he adds let's say glass, I will get a danknull in my last slot overwriting whatever was supposed to be there (lost a storage crate with resources this way) and it will have all his items in it, if I take out his cobble for example then his cobble is gone too.

Feel free to contact me if you need any other information.
Ahzu

**Comment by Rithsagea** [comment]
This is probably a separate issue, as it doesn't involve changing the mode. I suggest you make another ticket for this.
