### ISSUE TITLE
[Minecraft 1.12.2][v 1.4.43] Erratic behaviour when inserting items caused by #60 and #77

### ISSUE THREAD

**Issue by RionEV** [p455w0rd/DankNull#145]
Relevant issue tokens:
#60 and #77 

I maintain a personal modpack that allows the crafting of a dank/null/Creative that in theory should allow any player to have a limitless amount of any block that they desire in Survival mode. In practice, the dank/null/Creative does not appear to respect the fact that no blacklist or whitelist was set in the config.

The only workaround available appears to be to allow players to enter creative mode, disable the lock on their item, and insert the items that they want in their dank/null/Creative - however even with this workaround the behaviour of the item after switching back to survival mode is erratic.

Reproduction of issue: 
Give dank/null/Creative to player in Survival mode.
That player sets their game mode to Creative, unlocks the dank/null, and inserts the item they want (such as minecraft:glass), then locks it again.
Player returns to Survival mode.
That player attempts to remove a stack but the item is either duplicated, and ejected from the dank/null, or not present in the dank/null at all when it is reopened.
Note:
Items that would otherwise be added to a dank/null/Creative without changing the locking settings can be added in Survival mode as expected (such as minecraft:cobblestone or even minecraft:prismarine:1)

If at all possible, could a config option to disable the lock/unlock mechanic of the dank/null/Creative be included in the next release? This is meant to be a far-into-endgame item as it is configured in this pack, so allowing the placement of infinite amounts of any block is an intended side effect of this config change if implemented.

If the option to enforce unlocked behaviour exists (such as adding a single item to the blacklist like minecraft:bedrock) can this behaviour be more clearly explained in the configuration settings of the mod?

**Comment by p455w0rd** [comment]
this is intended behavior...the creative /dank/null is an item meant for pack developers to add items to, and the lock it..the pre-filled and locked version is what would be rewarded to players..you can, of course, just give them an unlocked version..i will consider a config option to disable locking entirely

**Comment by RionEV** [comment]
Thank you for the response - I have reloaded my minecraft instance to test this.

Your advice initially appeared to have worked - unlocking the item and then returning to Survival mode allowed previously restricted items to be inserted (without locking the item again), however seemingly at random, the lock will re-engage itself, and then the item will apparently update to eject the item that was inserted. Again, testing with glass;

Switched to creative mode, unlocked item, inserted glass, switched to survival mode : attempting to shift-click the item removes it entirely, attempting to click the item removes it entirely, and either way, the lock is re-enabled. At first it will appear that the stack can be placed back into the dank/null, but upon closing the inventory the items are dropped as though the inventory was closed while holding the item under the cursor.

Switched to creative mode, unlocked item, switched to survival mode, inserted glass : same behaviour.

Whether or not the locking mechanic is intended, it does seem to be misbehaving in this case - except the issue is not the blacklist not being respected but instead the lock, when the gamemode changes.

**Comment by p455w0rd** [comment]
i mean..it still isn't a bug..it's intended functionality..it's not meant to be able to be unlocked in survival...this was deemed to be "too OP"...shift-clicking items out while it is unlocked is the only way to clear a slot (in case a user accidentally puts in the wrong item or whatever)...it's intended behavior..but if u truly wish to have an item like this..i could add code to check the user's game mode and if they're in survival, just extract a full stack rather than deleting the stack

**Comment by RionEV** [comment]
I think I understand now, yes - if that's an option you can provide for pack devs, that would be kind of you, but knowing now that it isn't a bug I won't complain any further =P

The intent was to provide players on my priv server with a very end-game item without having to continually monitor who wants to have creative mode any more, so it being overpowered was something I'm aware of, and I understand your motivation to make it work like this now. Thank you for the information!
