### ISSUE TITLE
Can't use/open danknull

### ISSUE THREAD

**Issue by leafnlight** [p455w0rd/DankNull#146]
I can't open the danknull with shift+rightclick nor by dropping it on the ground. I went to the control settings to hotkey "open nearest \dank\null" and assigned Lshift+rightclick to it. I was then able to access the danknull, but the UI had erratic behavior, making items disappear and others to duplicate and I just couldn't make it work (items won't stay in it). It even removes my armor??? FYI I'm playing with the direwolf20 1.12 modpack

**Comment by Bismyth** [comment]
Had the exact same issue, i just installed the latest version from [here](https://minecraft.curseforge.com/projects/dank-null/files/2624277), don't forget to update the library as well found [here](https://minecraft.curseforge.com/projects/p455w0rds-library/files/2616339)
