### ISSUE TITLE
Is this, this mod or another?

### ISSUE THREAD

**Issue by RepoDraghon** [p455w0rd/DankNull#148]
bottom right, is this a part of Dank or is it another mod and how to I resize or get rid of it?
![javaw 2018-12-18 02-15-55-36](https://user-images.githubusercontent.com/8423696/50144408-6a9e6600-026c-11e9-837a-b327dce18142.jpg)

**Comment by p455w0rd** [comment]
It's /dank/null. It's not resizable. Remove the mod. (Or politely ask that a config option be added)

**Comment by RepoDraghon** [comment]
oh, ok, just making sure... no need to do anything, I just wasn't sure if it was like theoneprobe or Waila or some overlay mod. Thanks for the quick response :)
