### ISSUE TITLE
Shift+Right Click Opens Dank Null UI, Regardless of What Item is Held

### ISSUE THREAD

**Issue by Superplay64** [p455w0rd/DankNull#149]
Reporting a bug that occurs when you Shift+Right Click with any item in hand.  No matter what item you're holding, the Dank Null UI will open up if you Shift+Right Click.  It becomes annoying for items that require you to Shift+Right Click to use them (like the Thermal Expansion Crescent Wrench), or if you're trying to Sneakwalk while building a bridge for yourself.  The only exception to this I've noticed, is if you Shift+Right Click an item that has a UI of it's own (like the Actually Additions Drill).  From my testing (releases on 1.12), this bug only occurs in version 1.12-1.4.41 and newer, of the mod.

[Video demonstrating the bug.](https://www.youtube.com/watch?v=2irZa4ZEzx0)

**Comment by p455w0rd** [comment]
I commented on the video. I plan to push and update to Curse today. Help would be appreciated. :)
