### ISSUE TITLE
weird lang file behaviour

### ISSUE THREAD

**Issue by NicosaurusRex99** [p455w0rd/DankNull#15]
MC: 1.12.2
Forge: 14.23.0.2515
//Dank/Null: 1.0.10
pwlib: 2.0.22
Issue unlocalized names displaying
Media:
https://youtu.be/wqRY67lJWmw

**Comment by NicosaurusRex99** [comment]
https://www.dropbox.com/s/ekinaz2raky9o24/DankNull-1.12-1.0.10.jar?dl=0
Dank Null jar download
https://www.dropbox.com/s/icq8wlzd3r983j7/p455w0rdslib-1.12-2.0.22.jar?dl=0
Pw Lib download

**Comment by NicosaurusRex99** [comment]
@p455w0rd https://www.dropbox.com/s/trm9m87cx4zyrwx/N.zip?dl=0 Heres the curse instance
note, not all mods work yet having a minor issue with Extra util

**Comment by p455w0rd** [comment]
ty so much!
