### ISSUE TITLE
Boots of the traveler duplicating, /dank/null disappearing, related events.

### ISSUE THREAD

**Issue by Marvin21st** [p455w0rd/DankNull#150]
* **Modpack Version**: FTB presents Direwolf20 1.12
* **Issue**: While wearing boots of the traveler when opening /dank/null (yellow) and end up with a duplicate pair of boots and null box disappears. Sometimes comes back (have not worked out how or if this is repeatable) Only happens when wearing boots. Boots can be in inventory with no effect.

* **Link to Log or Crash File Paste**: <none

* **Is it Repeatable?**: yes
* **Mod/s Affected**: Thaumcraft, /dank/null

* **Known Fix**: log out and back in. always fixes. Sometimes it changes back but Im not sure how I did it.

**Comment by p455w0rd** [comment]
is this a single player world? if so, can you please join my discord and download the jar in #dank-null and tell if this issue still happens? https://discord.gg/8g62YV7

**Comment by Marvin21st** [comment]
Hi Have sent a dm through discord
