### ISSUE TITLE
/Dank/null deleting all block.

### ISSUE THREAD

**Issue by HeavyDeception** [p455w0rd/DankNull#151]
SO it seems that its not holding info correctly i'm using [1.12-1.4.46 (1.4.46)] in the mod pack enigmatic 2 expert Ver:1.51

image of what i'm trying to say.
![error danknull](https://user-images.githubusercontent.com/20760785/51082229-8872b580-16c8-11e9-8d2e-61c81c203da4.png)

**Comment by xAlicatt** [comment]
Definitely something weird going on since the last update...my players have reported items going missing from their dank nulls

**Comment by xAlicatt** [comment]
Just have them rollback versions...that's what I'm going to to do in my pack.

**Comment by p455w0rd** [comment]
I'll look at it after i wake up...i just have no idea what it could be

**Comment by Zang518** [comment]
Was using 1.4.46 rolled back to 1.4.43 as did not see this problem in 1.4.43
Can confirm the same weirdness. I thought the update may have did something to my current dank null so I removed all blocks and cheated myself a replacement. Something is happening where random blocks are in a sense being "deleting" or clearing themselves out of the null. Though, both times it happened with my original and current null, when I would shift right click the null to open it the missing blocks would be visible for like 1/10 a second, very very quick second then disappear. Only until I remove any blocks, do the missing blocks no longer appear for the very quick second or at all. Appears to be happening to random modded and non-modded blocks.

**Comment by xdarknecrox** [comment]
I'm not really sure but it seems to disappear after picking up a large amount of a single type of item. For example, picking up multiple stacks of cobblestone removed it from the null. Seems to occur with 2 or more stack (of 64) as well as at random times when opening the null.

This really sucks, I was so excited to using the null for the first time and I just see resources disappearing left and right.

**Comment by p455w0rd** [comment]
I'm aware of this issue...distracting me by making pointless repetitive posts only makes the update slower..have patience please
