### ISSUE TITLE
[Suggestions] Skip over non-placeable blocks when scrolling

### ISSUE THREAD

**Issue by TheFacelessOne** [p455w0rd/DankNull#152]
Hey, 

So you added the option to disable placement of a block from the dank null.

Could we skip those non-placeable blocks when shift+scrolling through the dank null?

ie. 
I've got 4 items in my dank null,
Item number 3 is not placeable, everything else is.
I would like to scroll from Item 2 to Item 4 without hitting Item 3 on the way

Hope this isn't too crazy a request.

**Comment by p455w0rd** [comment]
this is a good idea..I'll implement it when I get bugs fixed :)
