### ISSUE TITLE
Dank/Null not remembering selections

### ISSUE THREAD

**Issue by angiioh** [p455w0rd/DankNull#154]
When selecting an item for placement or selecting the extraction method, 99% of the time, my dank/null does not remember what I selected. 

In regards to placement selection, it will show the block I selected in the dank/null in my hand, but when I then place the block, it will place what was previously selected.

With extraction, I will select 'extract all' and it will usually go back to 'do not extract' or some other random extraction setting.

**Comment by JeremyFlorence** [comment]
I am also experiencing this issue with the dank null not remembering extraction settings.
