### ISSUE TITLE
ArchitectureCraft blocks inside the DankNull causes Client Crash

### ISSUE THREAD

**Issue by NielsPilgaard** [p455w0rd/DankNull#155]
Hey o/

As the title says, putting ArchitectureCraft blocks inside the Dank/Null/ causes a client-side crash. All ArchitectureCraft blocks have NBT data, and I believe use CodeChickenLib for rendering.

Would it be possible to prevent them going into the Dank/Null/, or catching the crash?

Relevant crashreport: https://github.com/NillerMedDild/Enigmatica2/issues/286

### Version
- Forge 1.12.2-14.23.5.2781
- DankNull-1.12-1.4.43

**Comment by Rithsagea** [comment]
This happened to me with Mekanism Energy Cubes.
It occurs when the render code on the other mod does weird stuff.

https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/client/render/item/CustomItemModelFactory.java

As seen here, the item's render methods are just throwing exceptions.

https://github.com/elytra/ArchitectureCraft/blob/1.12/src/main/java/com/elytradev/architecture/client/render/RenderingManager.java#L322

I'm going to assume this is what is causing the issue.
