### ISSUE TITLE
Opening Dank/Null/ causes contents to randomly disappear or shrink to 64 stack size

### ISSUE THREAD

**Issue by The-PurpleOrange** [p455w0rd/DankNull#156]
Running version DankNull-1.12-1.4.46, just updated from 1.4.43 which had no issues
Opening the Dank/Null/ causes items to randomly disappear or shrink their stack size.
Replications: 
Spawn in a dank null, spawn in 64 cobblestone, place in the dank null
Spawn in several more stacks of cobblestone, throw them on the ground and pick them up, 
Open the dank null by shift-clicking. 

Doesn't happen every time, but at least 50% of the time I lose everything or it gets reduced to 1 stack.

EDIT: I'm playing on a server if that is anything.

**Comment by jimnordb** [comment]
Having the exactly same issue. Rolled back to 43

**Comment by CyaNox** [comment]
Something is definitely going wrong as the NBT of this dank null is showing:

![javaw_2019-02-01_00-31-03](https://user-images.githubusercontent.com/211381/52092768-f23ffa00-25b8-11e9-854a-a79dbccdc646.png)

When opening this dank null the stone does not show up at all (The cobblestone shows 59 however this used to be way more in the past).

This happened for me in Stoneblock 2 version 1.3.0 so I should probably report it there however I saw this report here so wanted to add my additional info.

**Comment by thejams13** [comment]
Just stopped by to say I am having this issue too. Also on a server

**Comment by ShyMaiden** [comment]
Not sure if this relates to the same issue, but it sounds very similar.

I am currently playing project ozone 3, version 3.0.37, with mod version 1.12-1.4.46. When I am in my world alone, I have not had an issue with the dank/null. Whenever I open my world to lan and have other people join me, we have issues. If the other player uses the dank/null, it creates a new version in my inventory. This does not happen everytime, but very often. Once it deleted the item that was in that inventory slot for me.

Also, the player using the dank/null doesn't see the items he just put in it, but I see them in the duped one I got.

I confess to not being a very good bugreported (yet), so I may have missed important information. If so, I'd be happy to provide it, if pointed in the right direction. I have also mentioned this issue on the issue tracker for the modpack.

**Comment by dredhorse** [comment]
adding that a lot of the time also more than one stack is missing, just now all my cobblestone disappeared... hard cobblestone, dark cobblestone, normal one etc.. all ore dict to cobblestone

also (I'm not really sure) I think I saw one time the items show up in my camping backpack (but don't hold me on to that).

**Comment by dredhorse** [comment]
hmm.. might be related to https://github.com/p455w0rd/DankNull/issues/151

**Comment by thejams13** [comment]
i am roll back on my server I think your right about it being 




> hmm.. might be related to #151

**Comment by mcdodge34** [comment]
I can confirm having same issue, will roll back quickly, I've just lost a whole mining trip of ores.

**Comment by AGuyNamedSparre** [comment]
Working on a custom modpack and I'm having this issue on the 1.4.46 version of /Dank/Null on a server.

![image](https://user-images.githubusercontent.com/14899002/54316084-1837c180-459d-11e9-88d1-4f809b8b5993.png)

Cobblestone in the NBT is showing up as -128B and will delete itself once I try to do anything with the dankNull.

I managed to fix the issue by cheating in stacks upon stacks of cobblestone and picking them up off the ground. The value changed to 2B and proceeded to reset itself to 2 cobblestone, but seems to have completely corrected itself with even more cheated in cobblestone. The RealCount and the Count values are now the same and all seems fine and dandy.

**Comment by FuuNoKamiOka** [comment]
Throwing my hat into the mix here. On version 1.4.46 on server with the modpack Stoneblock 2 version 1.9.0. Anything I can do about this? It's honestly really annoying.

**Comment by Twisted-Code** [comment]
hmm... you guys didn't have this issue with build 43? Because I'm having exactly the symptoms you're describing, but with 1.4.43
(Really wish I knew about this issue before I spent an entire mining trip collecting emeralds to make the top tier)

**Comment by mcdodge34** [comment]
> hmm... you guys didn't have this issue with build 43? Because I'm having exactly the symptoms you're describing, but with 1.4.43
> (Really wish I knew about this issue before I spent an entire mining trip collecting emeralds to make the top tier)

Nope, never ever had any issue with build 1.4.43, beware that sometimes the twitch launcher doesn't write the correct version number in the mod list, you may still have the 46 build in your mods folder and the launcher tells you have 1.4.43

**Comment by Twisted-Code** [comment]
> 
> 
> > hmm... you guys didn't have this issue with build 43? Because I'm having exactly the symptoms you're describing, but with 1.4.43
> > (Really wish I knew about this issue before I spent an entire mining trip collecting emeralds to make the top tier)
> 
> Nope, never ever had any issue with build 1.4.43, beware that sometimes the twitch launcher doesn't write the correct version number in the mod list, you may still have the 46 build in your mods folder and the launcher tells you have 1.4.43

oh, you're right! Apparently, at least according to the info displayed on the "mod options" menu, this pack is actually using build 46. Stupid twitch...

**Comment by mcdodge34** [comment]
And most modpacks updated recently with this build of Dank/Null, I guess the modpack makers aren't aware of this bug, very very weird that they don't seem to notice this.

**Comment by p455w0rd** [comment]
So why am I not replying? Why is nothing being done? I must be 'just another dev that that doesn't care'. Well this has been reported tons. The amount of closed dupe reports of exactly this issue as well as open ones _with_ my replies is staggering. Every notification takes me away from development. Every time I reply, it takes me away from development. Impatience will not make my brain work any faster. Commenting after knowing this has been reported (replying only to "confirm the issue") is just impatience. I have been working on a full rewrite for quite some time. It was going smoothly, and it is technically functional, but is extremely inefficient due to my changing the inventory to rely purely on Forge's IItemHandler Capability. So I have started over again, 2 days ago, from a clone of the 1.12.2 branch of this repo. This time around I'm doing something I never wanted to do, but something that should have been done long ago to remove the hackyness that I use for stack sizes > 64. I cannot give an ETA, just know that, as with my other replies where I have already addressed this many times, I am working on it.

**Comment by mcdodge34** [comment]
Sorry I didn't mean you did a bad work there, just that modpack devs should be careful before upgrading mods in their packs so they don't end up with mod version that isn't working properly in a release of their modpacks. Kuddos for your hard work, its one of my favorite, I'm a all time hoarder.

**Comment by p455w0rd** [comment]
I wasnt targeting anyone in particular, just addressing what might be on peoples' minds...again...every notification and reply takes me away from dev...like right now and this reply..stop replying and it'll get done faster..just let me work :) if its any consolation, the update is actually going pretty good so far..no major road bumps so far...really hoping to get at least a functional interim release in the next day or two which will basically just be bug fixes to get a functional version out...after that new features n stuff will be added..the goal atm is to reduce code to eliminate possibility of error and ensure that it's truly error free as far as the syncing goes which is what's the current issue is.

**Comment by Twisted-Code** [comment]
> 
> 
> So why am I not replying? Why is nothing being done? I must be 'just another dev that that doesn't care'. Well this has been reported tons. The amount of closed dupe reports of exactly this issue as well as open ones _with_ my replies is staggering. Every notification takes me away from development. Every time I reply, it takes me away from development. Impatience will not make my brain work any faster. Commenting after knowing this has been reported (replying only to "confirm the issue") is just impatience. I have been working on a full rewrite for quite some time. It was going smoothly, and it is technically functional, but is extremely inefficient due to my changing the inventory to rely purely on Forge's IItemHandler Capability. So I have started over again, 2 days ago, from a clone of the 1.12.2 branch of this repo. This time around I'm doing something I never wanted to do, but something that should have been done long ago to remove the hackyness that I use for stack sizes > 64. I cannot give an ETA, just know that, as with my other replies where I have already addressed this many times, I am working on it.

don't worry, I'm sure most people (myself included) understand you're busy either trying to fix it in some way (as you explained is the case with your rewrite) or with real-life obligations. In my case, I simply replied here because I wasn't sure why I was (or thought I was) seeing this happen with build 63 (it turned out Twitch displays version numbers incorrectly. Now THAT is bad programming...). Not every reply here or dupe instance of the issue necessarily represents impatience. Some people, like myself, are just verifying that "yes, this happens" and the circumstances thereof. With a few unfortunate exceptions, I don't think anyone means to imply you're not doing your best. All that to say, don't take things so personally 😄

**Comment by p455w0rd** [comment]
I have a version I need tested. It's a hotfix of sorts that merely addresses the current dupe/sync/deletion issues. I will release another version with further optimizations/docking station functionality in the coming days, but before I push this to Curse, I need for someone who has access to a server to do some testing to try and replicate the bug(s) described here. I would like to be certain that these things are fixed before I go further. Contact me on discord if you can test this. [Discord](https://p455w0rd.net/discord)

**Comment by M3wM3w** [comment]
This happens to me too, tried with emerald and diamond dank. Mined some netherrack and fiery netherrack from netherex. Stack reduces and later all content in the dank is just wiped. Nothing left all deleted.
