### ISSUE TITLE
/dank/null duplicated itself

### ISSUE THREAD

**Issue by ghost** [p455w0rd/DankNull#157]
For some reason, my emerald /dank/null duplicated its contents in a different emerald /dank/null in my inventory, overwriting those. Both /dank/nulls were in my hotbar. Unfortunately I can't give any more information, it happened without me noticing. Is this a familiar bug? Any idea what might've caused it?

I'm running DankNull-1.12-1.4.46

**Comment by realTIMematrix** [comment]
Have the same issue. Got a second emerald dank/null but loosing the item that is in the slot with the duplicated dank/null. So i have lost my tinkers crossbow and a tinkers sledge hammer.

**Comment by Zedrimar** [comment]
Never happened to me, but it could be something with the world getting corrupted. Can you provide anymore info?

**Comment by BozoJim** [comment]
I experienced this glitch today. I am playing locally with another person using the Open to LAN server. I am not the host.
Whenever I interact with the /dank/null interface a /dank/null shows up in her inventory with all of the items in it replacing an from her hotbar. After two tools went missing we realized what was happening...
DankNull-1.12-1.4.46

**Comment by p455w0rd** [comment]
join [discord](https://p455w0rd.net/discord)..i'll be needing testers soon to test that all of the issues on the tracker have been fixed...I'll provide the server and test pack..just need testers

**Comment by SeanHolder** [comment]
Please post the fix for this as soon as it is available. I wish I could just disable this but it will not let me.
