### ISSUE TITLE
Extract deleting items and misbehaving

### ISSUE THREAD

**Issue by ShadwDrgn** [p455w0rd/DankNull#159]
on 1.4.46 when setting to extract all but one and then clicking on a stack less than 64 it extracts 1 and leaves none in the dank/null.

**Comment by Sourceshard** [comment]
I have had the aforementioned and further issues with this. I have items that can be scrolled through in my hot-bar that show lets say 356 items left to place, but opening up my cube I can not see them, if i click anywhere in my cube it deletes them entirely. I have also had items completely run out even though it is set to"Place all but 1". It will show an empty box where the item was in the cube. clicking it will reorganize the cube and remove the box.

**Comment by Dragon87tamer** [comment]
i have had problems to same version, when putting items into dank/null by picking up of ground (with set items in dank/null) it deletes all of that item leaving 0. IE, i have 3 dirt in inventory, place in dank/null so it collects, dig up dirt to have more in the dank/null, check to see how much i have, 0 is my answer :(

(seems like once it reaches 128 items it deletes the whole stack, if u have 127 items, its fine, add the last one, and the whole stack goes bye bye)
