### ISSUE TITLE
Docking station does not remain a full block when dank null removed.

### ISSUE THREAD

**Issue by NolanSyKinsley** [p455w0rd/DankNull#161]
When the dank null is in the docking station the station is considered solid from below, so you can attach things like a translocator to transfer items out quickly, but when you remove the dank null the block does not remain a full block so the translocator pops off as soon as it gets a block update. Even when empty it should be counted as a full block so when placed above hoppers it will stop them from checking for dropped items to pick up, reducing lag.

**Comment by progheal** [comment]
I think this is also the reason an EnderIO item conduit won't connect to a docking station.
If I put the docking station above an EnderIO item conduit, the conduit won't generate a connection like what it will have when a chest is put above it. Yeta wrench can't do anything about this connection even when a /dank/null is then docked.
On the other hand, if I put down a docking station and dock a /dank/null on it first, then put an item conduit below it, the item conduit readily connects to the docking station. From this point, as long as the docking station and the conduit is not removed, yeta wrench can easily change the connection state of this item conduit just like usual, regardless if the docked /dank/null is removed or not.

**Comment by p455w0rd** [comment]
This has nothing to do with it remaining a full block. If there is no /dank/null in it, then there is no inventory to access. I have been testing with Thermal Conduits in dev and they update properly. I'm not sure about EnderIO. Just to avoid headache, I can change the functionality internally so that the docking station always has an inventory, though.

**Comment by Twisted-Code** [comment]
I'm still having issues with Enderio conduits disconnecting from docking stations as of build 89. Appropriately, I'll open a follow up issue in a little bit so we can figure this out (hopefully)

**Comment by cc2k** [comment]
I have this same problem in the version of po3 modpack. (1.12.2)
Just to point out it still is there :D
