### ISSUE TITLE
Selecting an Extraction Option For a Stack bigger than 64 in a /Dank/Null and Attempting to Pull Items Out By Hand, Deletes All Other Items Except 1

### ISSUE THREAD

**Issue by Zedrimar** [p455w0rd/DankNull#164]
This is a bit of a weird one, but when I was using the tier 6 null (emerald) and selected an extraction option (thinking that it would only apply if it was docked), the item gets pulled out as a "single block" as it seems to be creating an item stack of invalid size. If the item is then thrown out of the inventory, all but 64 of the item will be returned. Do note that to reproduce this, the item stack MUST be pulled out by hand, directly from the null. Reproduced this on a tier 5 null too so this is shared through all of them

Good for clearing the quarry of stone in my pocket, but not so good when I have gold I need to turn to blocks. GG for backups, but this is one that can be troublesome for those not expecting it.

Let me know if you want a log file too, so far I can't find anything useful in my logs, but maybe you can find something, I don't know....

Mod Version: 1.4.46 (1.12.2)

Forge: 14.23.5.2815 (Also 1.12.2)

____________________________
Edit: Even simply cycling the extract options in a slot will produce the bug, even if it is set back to "do not extract". Also, everything works fine when on the docking station. I can't access the GUI when docked for some reason, but TheOneProbe shows that it is following the extraction option set

**Comment by Bandi42Plays** [comment]
I just had cobble disappear on me while mining. I opened the null to place a new block in and it just wasn't there anymore. It seems to be leaving around after 64 blocks. Sometimes it goes when I'm placing blocks from the null, sometimes they go when I open it up to add a new block. Lost a lot of coal today trying this mod out.

There's no error in the latest.log file either.
![image](https://user-images.githubusercontent.com/25653976/54657203-ddeb8a00-4a9e-11e9-835d-82487e2e9fcf.png)

Mod Version: 1.4.46 (1.12.2)
forge 14.23.5.2806 (1.12.2)

**Comment by joklbash** [comment]
Had the same thing happen to me. No errors logged.

**Comment by BrewingCoder** [comment]
Same mod/forge version as the OP and other posters and I can confirm.  I am having base vanilla stones completely disappear on me.  This is with an Emerald level item.  Cobblestone, Stone, and End Stone all vanish when you attempt to access them

**Comment by Ommina** [comment]
In my case, I added a stack of 25 blocks TO the emerald version.  Of the 43 item types that were already there, all but five were reduced to a count of "1".  Nothing in the logs.  Affected both vanilla and modded blocks.  With metadata and without.

I'm in a position to restore from a backup and get on with my day, but players on servers, do be aware.

**Comment by choekstr** [comment]
.46 version has several issues very similar to these.  revert to .43 while he works on his rewrite....
