### ISSUE TITLE
[1.12.2] Some Blocks Just.... Don't Place.... Like, At All....

### ISSUE THREAD

**Issue by Zedrimar** [p455w0rd/DankNull#165]
Not sure what causes it, or if it is just forge being derpy, but stairs don't place, minecraft's stone doesn't want to place, as well as just a whole bunch of random blocks... Weird... By won't place, I mean from the /Dank/Null, not from hand directly. So far I tried stone, stone brick stairs, and quark's permafrost. Permafrost places, stairs and smooth stone doesn't. Any ideas? Feel free to just close this issue, if it is intended (to prevent crashes) until a fix is available.

Mod Version: 1.4.46

Forge: *.2815 (1.12.2)

**Comment by p455w0rd** [comment]
still an issue in latest version?

**Comment by Zedrimar** [comment]
Sorry for being late about this, but yeah, it's still happening. I went into a test world with pretty much no other mods, and it seems like the /Dank/Null is trying to do creative mode placing or something, because it turns out that it's just limited to survival mode. When in creative, everything places just fine though. Any ideas?

**Comment by Zedrimar** [comment]
seems fixed now ^-^

I'll update here if it somehow breaks (which I doubt that it will, and it it does, it would probably just be some weird mod interaction)
