### ISSUE TITLE
Crashes server on startup

### ISSUE THREAD

**Issue by atvman36** [p455w0rd/DankNull#166]
We are trying to use the latest version and every time I add the mod. It crashes the server without fail during startup. I can remove it and it starts perfect. I have access to the crash log if that will help. For all I know there is a mod dependance for /Dank/Null, but I can't find any info to support that theory anywhere.

**Comment by BrockWS** [comment]
Please upload the crashlog to Pastebin or similar

**Comment by p455w0rd** [comment]
no reply..assuming solved
