### ISSUE TITLE
Dupe Glitch

### ISSUE THREAD

**Issue by 123Kappa** [p455w0rd/DankNull#168]
Pressing Q while hovering over an enemy in a dank null will toss the item on the ground and when you open the dank null again the item will be back into the dank null AND in your inventory.

**Comment by runescapejon** [comment]
I can confirm this work with version 
DankNull: 1.12-1.4.46
p455w0rdslib: 1.12.2-2.1.44
CodeChickenLib: 1.12.2-3.2.2.353
