### ISSUE TITLE
Opening the dank/null

### ISSUE THREAD

**Issue by Staegrin** [p455w0rd/DankNull#17]
Seeing as there is no config to set a keybinding to open the item I tried using the same method as with the old dev/null (Shift+right clicking the item while making sure you're not clicking on an object). Does nothing.

So I tried combining various mouse/ keyboard combinations and got nothing. Checked your curseforge page and found no mentioning of how to open a dank/null. You do mention "Alt+Left-Clicking on a filtered item while in a /dank/null GUI, will set that item as the selected item for that /dank/null" but this concerns actions while already in the GUI.

Version 1.0.11 /dank/null
minecraft 1.12.2
forge 14.23.0.2529

So you're my last hope. How do I open the dank/null? If it's conflicting with something I need to know first what it is I'm supposed to be doing.

**Comment by p455w0rd** [comment]
Crouch+right-click...
Try running an instance of /dank/null, CodeChickenLib, and p455w0rdsLib (latest of all of these) and tell me if you still experience..
![](http://p455w0rd.net/u/10.35.25-04.11.17.gif)

**Comment by Staegrin** [comment]
Clean install worked fine. I was also using the panels thinking they were the dank/null because they looked like the dev/null. Thanks for answering and sorry for wasting your time.
