### ISSUE TITLE
Crash on placing upper slab

### ISSUE THREAD

**Issue by wireman642** [p455w0rd/DankNull#171]
Crash to desktop on placing an upper cobblestone slab from a gold /dank/null

Only placing the top half from the null. Null holds the slabs OK and displays them but game locks up and crashes out when you place a solo top half cobble slab.

Tested on solid blocks (oak wood plank and cobblestone) and on top placed trapdoors.

Pack used: Poject Ozone 3 v3.0.39 

RAM allocated: 6144 MB
Total system RAM: 12 GB

**Comment by p455w0rd** [comment]
crash report?

**Comment by Shandoo94** [comment]
Also had a crash when placing a stone slab.

Crash report: https://pastebin.com/9UJWY4ij

**Comment by p455w0rd** [comment]
cool, thank you..I have it figured out, and it's fixed in the coming update

**Comment by p455w0rd** [comment]
see #153
