### ISSUE TITLE
Support for Shift-Click+Drag

### ISSUE THREAD

**Issue by MajorCooke** [p455w0rd/DankNull#173]
This would be highly appreciated, as so far it's the only mod that I've encountered where you can't hold shift, click on an item and then drag the mouse over other blocks to push items into a dank.

**Comment by p455w0rd** [comment]
ohhh...i've had this request before, but it wasn't put like this...I'll see what I can do :)

**Comment by MajorCooke** [comment]
Hahah, I can understand the confusion. It's just so weird how with everything else, it's super quick and easy to do that but I have to manually click each item just to get them into the tank when I bring them over into my inventory by hand.

Thanks!

**Comment by p455w0rd** [comment]
Like this?
![](https://puu.sh/DlL3d/d87208e229.gif)

**Comment by MajorCooke** [comment]
YES! **PERFECT!**

**Comment by MajorCooke** [comment]
This is exciting! I'm super stoked for it. :D 

Thank you so much for adding this.
