### ISSUE TITLE
[1.12.2] Sneak right click in SMP to place block

### ISSUE THREAD

**Issue by Morpheus1101** [p455w0rd/DankNull#18]
As per our discussion on Discord, could you have it so when sneaking right click on a block with /dank/null places highlighted block rather than opening the GUI plz :D

**Comment by ashly138** [comment]
Same here.

Make it like TAB + right click or let use pick the key we want it to be.

**Comment by Ozzymud** [comment]
Would love to see this as a user configurable keybind. At the moment it is akin to having the veinminer keybind set to sneak, very dangerous. I want to be able to set this to a keybind that I won't accidentally open a GUI at an inopportune time.

**Comment by ashly138** [comment]
the new stuff fixs nothing becaus your still using shift as a key

**Comment by p455w0rd** [comment]
@ashly138  no..is detecting whether the player is sneaking..so whateverr they have that key bound to..and yes..this is required..it is fixed in the latest version on curse..did u even try?

**Comment by ashly138** [comment]
must be sleeping a bit lols 

But yea its working nice :D

**Comment by p455w0rd** [comment]
either way..look at OP by @Morpheus1101 ..what he is talking about is how when you are crouching, moving backward, and trying to place blocks..before latest update, this would only work for blocks that were directly below you....i dunno wtf you're even getting at with keybinds..this issue is specifically for while the player is sneaking

**Comment by Morpheus1101** [comment]
You dont have to sneak to place a block, you can remain standing i guess you can call it. otherwise change the vinminer config option to use other keybinds other than sneak and it will solve the keybind issue

**Comment by p455w0rd** [comment]
this involves right-clicking..i don't see how that would conflict with veinminer unless they changed how it works..anyway..issue closed
