### ISSUE TITLE
[Crash on Login] After Shift Clicking Items Out - Unable to Log Back In

### ISSUE THREAD

**Issue by HalestormXV** [p455w0rd/DankNull#180]
https://pastebin.com/RN5PRrHT

Happens on version 1.12-1.4.46. Was shift clicking items out of the Iron Variant and then client crashed. SMP Server seems to be fine, problem is though I can no longer log into the game as I crash with the same error.

It is fixed by removing the playerdat file and NBT deleting the offending item (Iron Variant in my case) out of the inventory

**Comment by Requios** [comment]
Similar issue reported on my end - https://bitbucket.org/Requios/effortless-building/issues/41/client-crash-when-placing-dank-null-with
Current status: unable to replicate, need more detailed replication steps.

**Comment by p455w0rd** [comment]
[try dis plox](https://www.curseforge.com/minecraft/mc-mods/dank-null/files/2771911) and report back
