### ISSUE TITLE
Item doesn't show correctly

### ISSUE THREAD

**Issue by dagantang** [p455w0rd/DankNull#182]
when item in dank;/null 
it doesnt show the correct numbers of these block

**Comment by p455w0rd** [comment]
just tested, and it does

**Comment by Danekjovax** [comment]
(originally posted at https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/206)

Playing version 5.2 of Dungeons Dragons and Space Shuttles, and /dank/null version 1.12.2-1.5.71.

I've recently updated to the 5.2 version of the modpack, and noticed the following issues with the /dank/nulls that I have (I have 2x Mk VI):

GUI seems to have a synchronization issue (not sure if it's client or server based). Items aren't all displayed and pulling items from slots will not get the displayed item, or you can pull items from what you think is an empty slot. No duping is going on as far as I can tell. Items are supposed to auto-arrange from top-left, but in this case it is not visually happening.

Certain places prevent you from accessing the /dank/null GUI (hotkey or crouch/right-click). It may be related to if you have a block/entity in range of your crosshairs, but not totally sure.

Screenshots attached.  Thanks.
![2019-06-22_09 49 08](https://user-images.githubusercontent.com/10191173/59965263-9deed580-94d9-11e9-92a2-670fb644f998.png)
![2019-06-22_09 55 39](https://user-images.githubusercontent.com/10191173/59965264-a0512f80-94d9-11e9-9ced-a48b9f3e27ba.png)
