### ISSUE TITLE
Docking station item dupe bug

### ISSUE THREAD

**Issue by ThrillhouseGit** [p455w0rd/DankNull#183]
Bug: Left clicking an item in any tier /dank/null while in a docking station, and there are 64 or fewer of that item causes a full stack to appear, leaving the original (64-n) items inside the /dank/null untouched.

Shift left clicking while the /dank/null is in the docking station behaves as expected.
Left clicking an item while the /dank/null is in hand behaves as expected.

Fresh 1.12.2 Minecraft instance, new world.
Mods installed:
CodeChickenLib 1.12.2-3.2.2.353-universal
DankNull-1.12.2-1.5.71
p455w0rdslib-1.12.2-2.2.151
jei_1.12.2-4.15.0.268 (used for grabbing /dank/null in new world but issue remains even after saving world, removing mod, then reloading world)

Forge 14.23.5.2838

**Comment by HarryPeach** [comment]
Also experiencing this

**Comment by p455w0rd** [comment]
I noticed this as well when trying to work on the item version of /dank/null. Atm, in dev (and SMP), I actually have the docking station more functional than the item atm. Trying to get pwlib and /dnak/.null updates out tomorrow.
