### ISSUE TITLE
Item Dupe

### ISSUE THREAD

**Issue by happylacky** [p455w0rd/DankNull#185]
Bug: Item Dupe using two DankNull's

How to reproduce:
Get two DankNull's (also the danknull's can somehow dupe themselves I dunno how it happened but it happens)
Put the items you want to dupe in one danknull, and add a item that you don't want to dupe.
Quickly press the dankmenu key and switch to the empty danknull
You should now have the menu of the first danknull opened while having the second danknull in your hand (it appears that the game thinks you have the first opened even though you have the seconded selected)
drag out the item you don't want to dupe into your inventory (this causes the game to think your dragging out a item from the first danknull)
now close the menu, and re-opened it you should now have the items from the first danknull now in your second danknull
open your first danknull again and you'll see the item you didn't want to dupe is now missing from it. but you should have the rest of the items that you wanted to dupe

**Comment by p455w0rd** [comment]
good explanation but you didnt give any context (forge version, pwlib version, /dank/null version)

**Comment by happylacky** [comment]
ahh my bad forge version is 14.23.5.2821, /dank/null version is I believe 1.4.46 and if pwlib is your library its 1.12.2-2.0.36

**Comment by IMarvinTPA** [comment]
I was able to reproduce this in 14.23.5.2838.  danknull version 1..5.71, pwlib 1.12.2-2.2.151.
I bound the key, mousewheeled over the dank nulls in my inventory, hit the key while going over them.  I'm contemplating what this means.  I think there is an order of packets where it starts to open the GUI, inventory item change, GUI finishes opening on the dupe source, but continues with initial dank null.  I like the mod and want to keep it alive.  I'll see if I have any hope.

**Comment by p455w0rd** [comment]
[try dis plox](https://www.curseforge.com/minecraft/mc-mods/dank-null/files/2771911) and report back
