### ISSUE TITLE
mincraft crush dnk null

### ISSUE THREAD

**Issue by OriShahaf** [p455w0rd/DankNull#186]
..

**Comment by OriShahaf** [comment]
please help to resolve I can not play in mushroom stew mod pack by command.il

**Comment by p455w0rd** [comment]
1. Post logs using a site like [hastebin](https://hastebin.com) to post logs
2. No need to comment twice, it's not going to get the bug fixed any faster.
3. Check that this issue hasn't already been created..dupe of #181
