### ISSUE TITLE
Off-hand bugs

### ISSUE THREAD

**Issue by Dayyer1** [p455w0rd/DankNull#187]
In version 1.5.71, I can't get a /dank/null to place blocks if it is offhand. It can't pick up blocks that I drop, either. Also, if I switch it with the item selected in my main hand, a copy of the /dank/null will replace and delete the item. I can't seem to retrieve the deleted item.
If I use a /dank/null in my main hand, it works normally.

Happens with /dank/null 1.5.71 and Forge 2838

**Comment by Araxidis** [comment]
Exactly this comment. Can't place items with /dank/null in off-hand. Also, the main hand thing disappearing is an issue. I mean, it's kind of nice if you are into duplicating your /dank/null but who needs more than one?
