### ISSUE TITLE
Storing more than two stacks in null first hides and then deletes them

### ISSUE THREAD

**Issue by Muzarmo** [p455w0rd/DankNull#189]
Hi and thanks for a wonderful mod!

I got the exact issue described in issue #151, but in 1.5.71. When I store more than 127 items in the null (currently using gold), it first hides them, and later (when I close the null?) deletes them. I'm using a modified version of the Direwolf20 v2.5.0 modpack.

**Comment by Muzarmo** [comment]
For me, this issue only affects multiplayer.

**Comment by Fargoth8624** [comment]
Getting the exact same issue. I'm In FTB revelations 3.0.1, and I just manually updated the mod. Tooltip shows 640 cobblestone, Opening the dank/null shows no cobblestone, I can grab a stack out of the slot and then it displays 64 cobble.

**Comment by pentacore** [comment]
Thought i'd chime in and say that i experience the same issue

**Comment by Dalayeth** [comment]
Also having this issue on my FTB Revelations 3.0.1 server. Can't replicate on single player. When an item stacks over 127 blocks with any /dank/null/ opening said /dank/null will show a blank space and when closing it the items will disappear. If the /dank/null is never opened the items are not deleted and the /dank/null/ functions properly.

**Comment by PhoenixtheII** [comment]
FTB Stoneblock 2 v1.15.0 has this issue on multiplayer server too.

I put in a stacks of items, like 1500 cobblestone, open up the dank null emerald. And it shows nothing... When I click the first space. I get 64 cobble under my cursor.

This makes the mod completely useless.

**Comment by Captain-Oppai** [comment]
From what the dev said I believe this is already a known issue to to many duplicate issue reports. He is currently busy creating the rework. (From what I saw when looking for this issue.)
