### ISSUE TITLE
Crash when hovering over item in /dank/null inventory

### ISSUE THREAD

**Issue by Requios** [p455w0rd/DankNull#190]
1. Open /dank/null item with shift-rightclick (I used mk4)
2. Hover over any item in your inventory
3. Crash https://pastebin.com/NmfTeUqQ

**Comment by XLegacYX** [comment]
I'm having the same issue as well.

**Comment by XLegacYX** [comment]
I'm having a similar problem as well.

**Comment by p455w0rd** [comment]
update forge
