### ISSUE TITLE
Duplication glitch when opening dank null in off hand

### ISSUE THREAD

**Issue by noamsm** [p455w0rd/DankNull#192]
### Description
If you hold a dank null in your offhand, shift right-click, and try to take an item out of it, the dank null duplicates itself, overwriting the item I had in my main hand.
This might only happen when you shift-click the item into your inventory.

### Versions
MC: 1.12.2
Forge: 14.23.5.2838
Mod: 1.5.71

**Comment by p455w0rd** [comment]
[try dis plox](https://www.curseforge.com/minecraft/mc-mods/dank-null/files/2771911) and report back

**Comment by noamsm** [comment]
In the new update, you can no longer use the dank null in the offhand.
It fixed the duplication glitch but removed functionality... 
I'm fine with that but you may want to look into adding that functionality back.

**Comment by p455w0rd** [comment]
try this https://www.curseforge.com/minecraft/mc-mods/dank-null/files/2779753 please and report back
