### ISSUE TITLE
java.lang.NoClassDefFoundError: p455w0rd/danknull/items/ItemBlockDankNullDock

### ISSUE THREAD

**Issue by ZL1LAC** [p455w0rd/DankNull#195]
Server crash, not sure why.

Server Crash Log:
https://pastebin.com/Wgmxvyz7

Client Crash Log:
https://paste.dimdev.org/aqinewosar.mccrash

Forge-1.12.2-14.23.5.2838
DankNull-1.12.2-1.5.71
p455w0rdslib-1.12.2-2.2.156

**Comment by samtrion** [comment]
Same here ...

https://paste.dimdev.org/tifaputine.mccrash

**Comment by samtrion** [comment]
Switched back to p455w0rdslib-1.12.2-2.2.151.jar as workaround... :(

**Comment by brachy84** [comment]
Please upload new version. I can't update my pack

**Comment by ZL1LAC** [comment]
> 
> 
> Please upload new version. I can't update my pack

Or use 1.12.2-2.2.151 instead.

**Comment by p455w0rd** [comment]
[try dis plox](https://www.curseforge.com/minecraft/mc-mods/dank-null/files/2771911) and report back

**Comment by ZL1LAC** [comment]
Hello,

Working for me now.
