### ISSUE TITLE
Crash during mod loading

### ISSUE THREAD

**Issue by Zapdos333** [p455w0rd/DankNull#196]
During game start this crash happens:

[crash-2019-07-27_11.19.51-client.txt](https://github.com/p455w0rd/DankNull/files/3438014/crash-2019-07-27_11.19.51-client.txt)

**Comment by MokahTGS** [comment]
https://paste.dimdev.org/solobileno.mccrash

**Comment by 43eyes** [comment]
Use the most recent version of /dank/null and use THIS version of the library:
https://www.curseforge.com/minecraft/mc-mods/p455w0rds-library/download/2726877

Fixed it for me

**Comment by Zapdos333** [comment]
thx
game started wihout crash
