### ISSUE TITLE
DankNull Deleting Entire Stack of item.

### ISSUE THREAD

**Issue by cactusstyle** [p455w0rd/DankNull#199]
On a Direwolf20 Server.

Add item to Dank Null, Once the item hits a stack and any more items are added to it, it will completely delete the item inside upon opening up the Dank null interface.

**Comment by Complexity03** [comment]
I believe that the direwolf20 pack is using an outdated version of DankNull and that the bug was fixed in a newer release. Check if the mod is outdated and if it is, update to the newest release. This should fix the problem.

**Comment by Captain-Oppai** [comment]
It is a older version but I tried to update it and it still caused this issue. Maybe just mine because it's a slightly modified version of Direwolf20.

**Comment by Complexity03** [comment]
What version are you currently using? As far  as I know, the issue is supposed to be fixed in the newer versions. If you tell me the version, I will try to replicate the problem you're having.

**Comment by katubug** [comment]
My players have reported this issue in every version we've used except 1.4.43.

**Comment by p455w0rd** [comment]
[try dis plox](https://www.curseforge.com/minecraft/mc-mods/dank-null/files/2771911) and report back

**Comment by katubug** [comment]
I tested both in an environment with just /dank/null and p455w0rdlib, as well as just plugging the most recent update into my modpack, and both seem to be functioning as intended. I only tested for about ~5 minutes but I didn't see any items being deleted. Thank you!
