### ISSUE TITLE
I RAISE AN ISSUE/IDEA !??!?!!11!1ONE

### ISSUE THREAD

**Issue by OGArist0tle** [p455w0rd/DankNull#20]
Could there be a selection option with the dank null docking station where the station will remove all but one of the item.

Thank you.

I'll show myself out.
![clhrzshuyaeguxc](https://user-images.githubusercontent.com/19681856/32637568-938753f0-c588-11e7-9599-d48dcb124a51.jpg)

**Comment by p455w0rd** [comment]
ogaPlz & kthx
