### ISSUE TITLE
:Thinking:

### ISSUE THREAD

**Issue by knoxhack** [p455w0rd/DankNull#200]
🤔

**Comment by knoxhack** [comment]
oops:
https://gist.github.com/knoxhack/cef16f468d297db6dc831e93223cd108

**Comment by knoxhack** [comment]
random start crash with:

forge-1.12.2-14.23.5.2838
DankNull-1.12.2-1.5.71
p455w0rdslib-1.12.2-2.2.156

**Comment by p455w0rd** [comment]
[try dis plox](https://www.curseforge.com/minecraft/mc-mods/dank-null/files/2771911) and report back
