### ISSUE TITLE
Not voiding...

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [p455w0rd/DankNull#202]
Downloaded the latest version. Got the red dank null cube. Got 128 cobblestone inside it. Keep mining, and my inventory fills up with cobblestone. What do?

**Comment by Slammyyyy** [comment]
Can confirm the same issue, seems to happen with all tiers, as it has been happening with my MK III as well. Once it hits the stack limit it just continues to fill the inventory. For me the temporary fix has just been to use the openblock's /dev/null alongside the dank null exclusively for cobblestone so its a bit easier to manage lol.

Edit:
Just tested it a bit more, it still voids new items if you try and put them in an already full dank null, but if you try to insert items of the same type as ones already inside, it will not void them.

**Comment by p455w0rd** [comment]
Appreciate the reports. Is this single player by chance?

**Comment by dinkygnatbane** [comment]
I had this happen in single player.

**Comment by Unrepentant-Atheist** [comment]
Single player, aye.

**Comment by CandiceJoy** [comment]
Can confirm.  SMP here.

**Comment by avidgamer5918** [comment]
I had the same issue on multiplayer

**Comment by Venrixia** [comment]
Dank null of all sizes have been observed not picking up & voiding blocks once full, Mark VI is the exception as that thing is huge, but it's possibly doing it.

Had this issue on a server running
SpongeForge : 1.12.2-2838-7.1.7-RC3902
Minecraft Forge : 14.23.5.2838
Danknull : DankNull-1.12.2-1.6.77.jar

Reproduced in singleplayer with a pack consisting of
Minecraft Forge : 14.23.5.2838
DankNull-1.12.2-1.6.77.jar
p455w0rdslib-1.12.2-2.2.156.jar

**Comment by p455w0rd** [comment]
try this and report back please: https://www.curseforge.com/minecraft/mc-mods/dank-null/files/2779753

**Comment by caighan** [comment]
that update definitely fixed it for me. thanks mate

**Comment by Venrixia** [comment]
Retried using DankNull-1.12.2-1.6.79.jar and it works as intended, thanks.

**Comment by Directhit124** [comment]
I tried this, then my game would crash on startup. Saying i need the updated lib file. so i did that and it still crashes.

**Comment by Jaq112** [comment]
DankNull-1.12.2-1.7.94
p455w0rdslib-1.12.2-2.3.161

Stopped voiding again. 

reverting to DankNull-1.12.2-1.7.79 and p455w0rdslib-1.12.2-2.2.156 makes the sound not work.

**Comment by SansDerp** [comment]
Can confirm, update has caused voiding to stop. Can also note some items will be stuck at 64 even if more are in the danknull, with some items turning invisible. Am still able to interact with the invisible items.

**Comment by pixelblob** [comment]
Same issue here
