### ISSUE TITLE
Use with thermal expansion issue

### ISSUE THREAD

**Issue by Hammy47** [p455w0rd/DankNull#204]
On the latest version, 1.6.77, I'm having issues with Thermal Expansion in and this mod.
Any kind of non-vanilla ingot turns into Pulverized Iron.
Any kind of non-vanilla gear turns into an Invalid Item.
Any kind of non-vanilla plate turns into a Pulverized/Blend/Dust of whatever plate it was.
Pyrotheum dust turns into Pulv Iron, Cryotheum dust and Blizz powder turns into Pulv Gold.
Aerotheum, Petrotheum, Mana Dust, Basalz Powder and Blitz Powder turns into an Invalid Item.
That's all I've tested.

**Comment by Hammy47** [comment]
I should say, this was never something that happened with the previous version.

**Comment by Morpheus1101** [comment]
I just tested this in the pack i play and i cant re-produce, all the copper/silver/lead/yellorium etc all crush to there respective dusts aok.

**Comment by Hammy47** [comment]
Ehh, could be an issue that I caused, the pack I'm playing doesn't by default have the mod in, I added it in on my own, so I could've screwed something up there? Idk.

**Comment by Frikkle** [comment]
That could very well have been the case. Could you try reproducing the issue in a setup with just Dank Null and Thermal Expansion to check if it persists?

If it doesn't I would recommend asking in the modpack's discord or support channels.

**Comment by Hammy47** [comment]
Just tested it out with only Thermal Expansion and Dank Null, problem is still happening.
[Mods](https://imgur.com/a/o7s8udz)

**Comment by Ethryan** [comment]
Can you check the ingots so they don't have a combined oredict,

for example IngotAny.

If they do maybe you can blacklist that oredict in dank null config.

**Comment by p455w0rd** [comment]
![](https://puu.sh/Eebw5/3c6644bbed.gif)

No idea what you're doing, but I can't reproduce this.
