### ISSUE TITLE
handler extraction functionality backward

### ISSUE THREAD

**Issue by p455w0rd** [p455w0rd/DankNull#206]
i derped and reversed the functionality between the Tile and Item ItemHandlers...the logic in the overriden methods in the tile should be swapped with the default implementation

**Comment by inspiiree** [comment]
Will this be fixed quickly? or is it exclusive too newest version only

**Comment by p455w0rd** [comment]
working on it now

**Comment by inspiiree** [comment]
> working on it now

Is it game breaking or can it used for a day or two?

**Comment by p455w0rd** [comment]
it's good..just that item extraction mode rules arent being applied properly when its on the dock so all item are extractable from outside blocks (like if you hook up an AE2 storage bus to the dock)

**Comment by inspiiree** [comment]
Okay, well I'm not that far into my mod pack yet lol
