### ISSUE TITLE
Crash When I/O Dank Null Manually

### ISSUE THREAD

**Issue by caighan** [p455w0rd/DankNull#207]
I updated to 1.6.79 today to fix the not voiding bug and since then every time I try and input or output from the danknull through the sneak click main interface it crashes my client. This is in a private multiplayer server with no one else on.

crash report below link to pastebin as I suck at all this bbc code for forums.
https://pastebin.com/fkHR1QCA

**Comment by p455w0rd** [comment]
please try this: https://www.curseforge.com/minecraft/mc-mods/dank-null/files/2780194
