### ISSUE TITLE
Latest version causes crash with Ex Nihilo Creatio

### ISSUE THREAD

**Issue by theshadowake** [p455w0rd/DankNull#209]
When attempting to place a mesh in a sieve, the following crash report happens:

https://paste.dimdev.org/sosovixesu.mccrash

Dank Null is listed as the cause and indeed, rolling back a version fixes it.

**Comment by BrockWS** [comment]
This is a Ex Nihilo Creatio bug. Please report it to them. https://github.com/BloodyMods/ExNihiloCreatio

**Comment by p455w0rd** [comment]
I really didnt think anyone used the DankNullUtils class since it wasnt part of the API, otherwise I would have properly deprecated..Apologies to @BloodworkXGaming

**Comment by p455w0rd** [comment]
submitted PR: BloodyMods/ExNihiloCreatio#265
