### ISSUE TITLE
[Question] all dank/null slot capacities?

### ISSUE THREAD

**Issue by Twisted-Code** [p455w0rd/DankNull#212]
I wasn't sure where else I could ask this, seeing as you have comments disabled on your curseforge project: what is the capacity per slot for each tier of DN, and how did you decide on the numbers anyway? For the first question, I would probably have to spend a lot of time spawning in stacks to find out that way, and for the second I don't see a mathematical relationship between the numbers (despite trying to find one for the sake of approximating tiers 4 and 5) which got me curious.

**Comment by p455w0rd** [comment]
check the JEI info tab for each tier

**Comment by Twisted-Code** [comment]
Ah! Missed that. Sorry!

**Comment by Twisted-Code** [comment]
perhaps that info could be added to the item tooltip if it's not too much trouble? Just a thought!
