### ISSUE TITLE
Extraction mode not obeyed by Docking Staion

### ISSUE THREAD

**Issue by BitsOfbitsOfBits** [p455w0rd/DankNull#215]
Hi:)

Since the last update the docking station will extract even with "Extraction Mode: Do Not Extract" set for a block or item.  I've tried EU transfer nodes and Enderio conduits, connecting to top and bottom, sending to chests and Storage Drawers/controllers/slaves.  My current DankNull is a tier 5, but I've cheated in a lower tier with the same issue.

I'm not using a "pack" (new to modern minecraft!) but about 100 mods added manually, single player.

**Comment by maxlowry123** [comment]
I am also having the same issue on a server.

**Comment by RobertLSnead** [comment]
same as well but when using a normal hopper

**Comment by p455w0rd** [comment]
fixed in [this update](https://www.curseforge.com/minecraft/mc-mods/dank-null/files/2829709) - keep in mind that you will need [this version of p455w0rdslib](https://www.curseforge.com/minecraft/mc-mods/p455w0rds-library/files/2829707) as well
