### ISSUE TITLE
Dank Null, CodeChicken Lib Crash on Spawn, Cannot Launch Game

### ISSUE THREAD

**Issue by theJERMwarfare** [p455w0rd/DankNull#216]
Stoneblock2 Mod pack on a dedicated hosted server updated to the latest version from FTB.

Scrolling thru dank null contents with r-shift scroll wheel crashed game.

Every login attempt since crashes the game before the world can load.

Crash log below:

[danknul_minecraft crashlog_10-1-19.txt](https://github.com/p455w0rd/DankNull/files/3678731/danknul_minecraft.crashlog_10-1-19.txt)

**Comment by theJERMwarfare** [comment]
After many Google searches and a few hours of playing with client settings I backed up my server side user inventory file, and edited it with NBTExplorer. After trying to move the dank/null to different inventory slots and deleting individual items out on the dank/null inventory without success I finally deleted the dank/null out of my inventory and the game will now launch without crashing.

**Comment by p455w0rd** [comment]
fixed in [this update](https://www.curseforge.com/minecraft/mc-mods/dank-null/files/2829709) - keep in mind that you will need [this version of p455w0rdslib](https://www.curseforge.com/minecraft/mc-mods/p455w0rds-library/files/2829707) as well
