### ISSUE TITLE
[Bug?] certain items behaving strangely/not going into dank when picked up

### ISSUE THREAD

**Issue by Twisted-Code** [p455w0rd/DankNull#217]
I've noticed certain items, including but (probably) not limited to Tin Nuggets (but not tin ingots or its pulverized form) from Thermal Foundation and Menril Wood Planks from Integrated Dynamics, behave strangely and will not be pulled into a dank on-pickup, even if there is already a stack in it. Furthermore, although toggling extraction mode to something besides "do not extract" seemed to make it accept the planks (for some reason), it did not work for the nuggets and after I toggled that, it seemingly started causing problems with a mod that integrates with this (Building Gadgets, specifically. I'll elaborate on that issue in a separate report on their tracker).
Possibly related to #204. One of the items in question, the tin nuggets, is a sub-item of thermalfoundation:material, and it sounds like the other bug is related to that same item and/or its subitems. That said, it does seem odd that I've only seen this happen with tin nuggets, not ingots, dusts, or any other form of TF's "material" item...
I'll provide a log later, after I try to reproduce this in a more controlled environment than my server with 154 mods...

**Comment by Twisted-Code** [comment]
I can't reproduce it on a scaled-down modpack, nor in a single player world the usual pack… so the massive logs from the server and connected client will have to do. Perhaps it has something to do with exactly the order in which items are registered or an interaction with my server plugins?
Anyway, here's the logs from my current sessions of the game (both sides):
[debug.log (server)](https://github.com/p455w0rd/DankNull/files/3698674/debug.log)
[debug.log (client)](https://github.com/p455w0rd/DankNull/files/3698679/debug.log)
PS: if you want to add some extra logging around the point in the code where it detects item pickups, I'd be willing to run a special build on my client for you. This one has been a pain in my rear for a while now.

**Comment by p455w0rd** [comment]
thank you for a great issue :) I'll look into this

**Comment by p455w0rd** [comment]
i believe this is probably related to the same bug as #220 and should be fixed in the next update

**Comment by Twisted-Code** [comment]
good to hear! I'll check out the next update whenever you release it and see if I continue to have issues. It sounds plausible as a solution, but I don't think I had other things with the same oredict entries for the two items I noticed this happen with. We'll see though.

**Comment by Twisted-Code** [comment]
what version is this supposed to be fixed in? I thought I updated to build 84 (the build that apparently included the fix for renamed Danks losing their custom name), but apparently I didn't, so I probably just need to update. Nonetheless, I wanted to check what version is the minimum to get the fix for this. Thanks!
