### ISSUE TITLE
[Compatibility/Feature Request] Angel Block placement

### ISSUE THREAD

**Issue by chaosblad3** [p455w0rd/DankNull#219]
The Angel Block from Extra Utilities is a special block that can be placed in the air aprox 1-2 blocks in front of the player in whatever direction they are facing (inc diagonal) without needing an existing block to be placed against.

Unfortunately this functionality does not work when trying to place an Angel Block from inside a Dank/Null, I was hoping you could add this as a compatibility feature, so that if the currently selected block in the Dank/Null is an Angel Block then it will utilise the same air placement function.

Alternatively if you wanted, you could replicate the same functionality into your mod directly, giving the Dank/Null itself the ability to place the currently selected block (of any type) in the air with a hotkey toggle to switch between normal and air placement mode, possibly on a per block basis (so for example I could set only glowstone blocks to be placeable in the air).

**Comment by p455w0rd** [comment]
implemented in [this update](https://www.curseforge.com/minecraft/mc-mods/dank-null/files/2829709) - keep in mind that you will need [this version of p455w0rdslib](https://www.curseforge.com/minecraft/mc-mods/p455w0rds-library/files/2829707) as well
