### ISSUE TITLE
requires nonexistent version

### ISSUE THREAD

**Issue by that1dog** [p455w0rd/DankNull#22]
version 1.0.12 requires codechickenlib 3.1.4, as of the moment im posting this the latest version is 3.1.3

**Comment by p455w0rd** [comment]
yup this was fixed in the latest version...3.1.4 does exist, but only on maven

**Comment by covers1624** [comment]
... Seriously, only dep with what's on curse, if it's not released, don't use it.

**Comment by p455w0rd** [comment]
It was a mistake due to having `deobfCompile "codechicken:CodeChickenLib:1.12-3+:universal"` in build.gradle ..I was using 3.1.3.313 locally, it just did that when I built. I changed that now though :)
