### ISSUE TITLE
[Compatibility/Bug] OreDict enabled Items inside DankNull scan for any match

### ISSUE THREAD

**Issue by Icpmcp** [p455w0rd/DankNull#220]
Blocks that have multiple OreDict entries due to other mods will be converted to the block inside the cube on pickup.

Example: The Immersive Railroading mod adds a few blocks to a new OreDict entry called railBed.
In the example I will show Oak Wood and Sand.

Here the DankNull with one piece of Oak Wood
![img](https://user-images.githubusercontent.com/57525861/68469529-a5114880-021a-11ea-8486-f0da311f8a01.png)

Notice the two OreDict entries and the enabled OreDict mode.

Sand has the same railBed entry below its usual sand entry
![img](https://user-images.githubusercontent.com/57525861/68470160-cc1c4a00-021b-11ea-87e2-2cc52886d5f2.png)

After mining one piece of Sand and picking it up
![img](https://user-images.githubusercontent.com/57525861/68470562-97f55900-021c-11ea-8b6c-002ee31d7df9.png)

Now I have two pieces of wood but no sand and until I turn off the OreDict function of the DankNull any item with the railBed entry that I pick up will be converted to Oak Wood.

Not sure if there is a simple way to fix this by just checking if all OreDict entries of an item match the entries of the item that was picked up.

For the time being I'll just turn off the OreDict mode for items with 2 or more OreDict entries.

**Comment by p455w0rd** [comment]
can you try adding `railBed` to the ore dict blacklist in DankNull.cfg

**Comment by Icpmcp** [comment]
I've added `railBed` to the blacklist:

![blacklist](https://user-images.githubusercontent.com/57525861/68981158-d08bc880-0802-11ea-9772-2da62d2c0d84.png)

However the problem still persists:

![image_1](https://user-images.githubusercontent.com/57525861/68981397-80f9cc80-0803-11ea-9d80-2f5cc724f9e2.png)

once again mining one piece of sand and picking it up:

![image_2](https://user-images.githubusercontent.com/57525861/68981299-3ed08b00-0803-11ea-98e4-917a92f44aed.png)

I can also try uploading a video of this if you want me to.
