### ISSUE TITLE
Rendering issue crashing game when opening inventory

### ISSUE THREAD

**Issue by FR3D99** [p455w0rd/DankNull#221]
I typed dank in my ME system and it crashed my game, error report https://paste.dimdev.org/moriromuxi.mccrash

Now, every time I open my inventory, game crashes due to trying to render dank null in JEI with an ArrayOutOfBoundsException
https://paste.dimdev.org/ihubovatic.mccrash

**Comment by p455w0rd** [comment]
remove optifine and if it still happens, reopen this issue
