### ISSUE TITLE
weird render Issue with Dank/Null shaders on the item

### ISSUE THREAD

**Issue by CitiesXL2815** [p455w0rd/DankNull#224]
**Issue:**
I don't know if it been report But there weird render issue with item dank/null shaders effect on the item not in hand (Maybe it is too) on hotbar or inventory and others when it shown causes the issue of rendering to appear The item causes weird block issue Something in the config fixes it only on Version: 1.6.77 But updating version: 1.6.80 and 79 breaks it completely I'll send pics of it
**===============================================**
**not broken**
![2019-10-13_17 20 10](https://user-images.githubusercontent.com/8730524/69106408-1a52f980-0a23-11ea-8ba8-69dd3f77e6cf.png)

**broken**
![2019-10-13_17 52 51](https://user-images.githubusercontent.com/8730524/69106450-38205e80-0a23-11ea-97ac-664c57f5be38.png)

**===============================================**

- **Versions affected:**
- **Dank/null version;** 1.6.79 and 80
- **Minecraft Version:** 1.12.2
- **Forge Version:** 2847
- **p455w0rdlib Version:** 2.2156
- **Optifine:** not installed
- **Server/SP:** SinglePlayer

**===============================================**
**Config:** 
 # Make items ultra shiny! [default: false]
    B:SuperShine=true <---- turning it to true fixes it
**only works in version:** 1.6.77 then broken after updating to next version

**Comment by CitiesXL2815** [comment]
forgot to add the log https://gist.github.com/CitiesXL2815/bbe389d380d3279c18b3e2ffbf7bef32

**Comment by p455w0rd** [comment]
I've removed shaders in the next update, so this won't be an issue :)

**Comment by CitiesXL2815** [comment]
okay thx
