### ISSUE TITLE
[1.12.2-1.7.84] Corrupted textures

### ISSUE THREAD

**Issue by mikan9** [p455w0rd/DankNull#225]
When downloaded from CurseForge, the assets .PNG files are corrupted and the textures show up as the default "Missing Texture" magenta/black checkered texture. "PNG file corrupted by ASCII conversion", according to Photoshop. The assets in the repo does however work.

**Comment by p455w0rd** [comment]
good catch..i'm stumped as to why this happens..every time i build now, it copies corrupted pngs to the final jar..i don't know why

**Comment by Protheus** [comment]
Similar to this issue: https://github.com/p455w0rd/WirelessCraftingTerminal/issues/361

**Comment by p455w0rd** [comment]
finally figured out a workaround...
