### ISSUE TITLE
[1.12.2-1.7.84] Extraction mode not obeyed in docking station

### ISSUE THREAD

**Issue by mikan9** [p455w0rd/DankNull#226]
Coal, Lapis, Iron Ore and some Thermal Foundation Ores' (Lead, Tin) extraction mode is still not being obeyed in the docking station.
Glowstone Dust, Redstone and Thermal Foundation Aluminum Ore does however work as intended.

**Comment by p455w0rd** [comment]
yeah my issue this entire time of dealing with the docking station has been due to extraction mode needing to be obeyed by other tiles, but not by player accessing the GUI..i've actually finally fixed it i think..in testing so far things are finally behaving in every test scenario
