### ISSUE TITLE
Crash after dock extraction

### ISSUE THREAD

**Issue by sine707** [p455w0rd/DankNull#228]
After I set all items to "Extract all but 1" and sat it on the /dank/null dock, I had xnet extract all its contents to a refined storage network.

After I tried to access it again the game crashed.

I attached the crash report.
[crash-2019-11-21_03.24.24-client.txt](https://github.com/p455w0rd/DankNull/files/3872511/crash-2019-11-21_03.24.24-client.txt)

**Comment by p455w0rd** [comment]
update /dank/null pls
