### ISSUE TITLE
Null clears on upgrade

### ISSUE THREAD

**Issue by KindarConrath** [p455w0rd/DankNull#23]
I noticed that if I have been using a Null cube and I decide I want it bigger, upgrading wipes the inventory.

It would be nice to keep the inventory when upgrading, maybe allow a self craft MKII->MKII to clear the item if desired

**Comment by p455w0rd** [comment]
That is how it's supposed to function..i'll look into it, thanks for reporting!

**Comment by KindarConrath** [comment]
if its actually a bug (not a feature suggestion) then I will do a bit of info reporting!

MC 1.12.2
FV: 14.23.0.2531
DN: 1.0.13

in DW20 1.12.2 pack
tested on a server

**Comment by KindarConrath** [comment]
nvm, tried again, can't duplicate... not certain what happened

**Comment by KindarConrath** [comment]
issue is intermittent, usually upgrades just fine, rarely wipes inventory

**Comment by p455w0rd** [comment]
looking at the code..it should never work lol..I didn't implement that in 1.12..i'll get it figured out..thanks again :)

**Comment by KindarConrath** [comment]
np, i'm still doing some research, I think I have found it, just doing some testing in an isolated instance

**Comment by p455w0rd** [comment]
i was wrong..i do have the code :) https://github.com/p455w0rd/DankNull/blob/1.12/src/main/java/p455w0rd/danknull/init/ModEvents.java#L57-L68

**Comment by KindarConrath** [comment]
ok, clicking on the result box+panes->upgrade works
SHIFT+clicking on the result box+panes-SHIFT>upgrade clears inventory

tested in instance with JUST DN & JEI

**Comment by p455w0rd** [comment]
erm..I don't quite understand lol possible you can make a gif/recording of this happening? (ShareX is an awesome program for this if you don't have one)

**Comment by KindarConrath** [comment]
will do

**Comment by p455w0rd** [comment]
just reproduced it..VERY weird..it seems the event doesn't fire when shit-clicking out of the result slot..I'll have to hack something in to get that to function properly

**Comment by KindarConrath** [comment]
darn, and I downloaded & learned how to use ShareX, created a GIF just for you!

**Comment by p455w0rd** [comment]
the event does get fired, but I think I know what's going on..this is a good find..I'll have to implement a custom recipe for this..thanks for all of your help :)

**Comment by KindarConrath** [comment]
NP, glad I could help :) I love bug hunting!

**Comment by p455w0rd** [comment]
![](http://p455w0rd.net/u/09.40.13-17.11.17.gif)

**Comment by p455w0rd** [comment]
https://minecraft.curseforge.com/projects/dank-null/files/2500899
