### ISSUE TITLE
Crash with ore dict config

### ISSUE THREAD

**Issue by Cazadorsniper** [p455w0rd/DankNull#232]
hypnotizd:
Loaded the latest version of Kappa, pulled my tier 1 redstone dank null out of my storage rack and put on my hot bar and immediately crashed
https://pastebin.com/eu4VESsP
I loaded back up and tried selecting it on the hot bar by scrolling my mouse wheel and as soon as it would highlight it crashes instantly.

**Comment by ghost** [comment]
I'm getting the same crash. :(

Note that the server did not crash, only the client. here's the crash log:
https://pastebin.com/ihj65ELb

Minecraft 1.12.2
Forge 2847
/dank/null 1.7.88
pwlib 2.3.161

**Comment by ghost** [comment]
Verified fixed in 1.7.89. Thank you @p455w0rd for all your work!
