### ISSUE TITLE
DankNull Turns flint into cobblestone

### ISSUE THREAD

**Issue by Florentoptennoort** [p455w0rd/DankNull#236]
whilst using the newest version of the DankNull mod it appears the DankNull registers flint as cobblestone. Whenever flint is picked up by the player it is automatically added to the DankNull as cobblestone except when there is NO cobblestone in the DankNull present.

If flint is in the danknull without cobblestone flint is picked up as flint. Whenever cobblestone is added to the danknull new flint will be converted to cobblestone. When flint is Shift clicked into the danknull it turns to cobblestone as well when cobblestone is already present.

**Comment by cjm721** [comment]
Unable to reproduce.
