### ISSUE TITLE
ProjectRed gem issue with Dank Null

### ISSUE THREAD

**Issue by timmit99** [p455w0rd/DankNull#239]
**Describe the bug**
Upon placing a ProjectRed gem (Ruby, Sapphire, Peridot) into Dank/Null they are replaced with 4 Circuit Plates from project Red

**To Reproduce**
1. Acquire Gems
2. Open Dank Null
3. Insert Gems
4. *Don't* profit.. the expensive gems are converted to Circuit Plates

**Expected behavior**
Gems do not transmute upon storage

**Crash Log**
N/A no crash

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
#
* MrTJPCore Version: MrTJPCore-1.12.2-2.1.4.43-universal.jar
* ProjectRed Version: ProjectRed-1.12.2-4.9.4.120-_______.jar
* /dank/null Version: DankNull-1.12.2-1.6.77.jar

**Screenshots/Videos**
![ProjectRed Bug](https://user-images.githubusercontent.com/8399317/70489016-7a8c0700-1ac8-11ea-9b6a-204f3bf8f1c5.gif)

**Comment by nickalbrecht** [comment]
I ran into a similar bug but with Thermal Foundation while playing with FTB Revelation. A lot of resources (ingots) where being converted to pulverized iron upon being added to a /dank/null. And some were actually being added as "Invalid Item (Destroy)".

https://github.com/FTBTeam/FTB-Revelation-2/issues/339

**Comment by cjm721** [comment]
Does not appear to still happen in latest. Most likely was fixed in #263
