### ISSUE TITLE
Dank Null Crash

### ISSUE THREAD

**Issue by knoxhack** [p455w0rd/DankNull#240]
Random crash while playing

Crash:
https://paste.dimdev.org/gufesoniwi.mccrash

**Comment by Terminal-Access** [comment]
Just updated to the latest version and the support library and I am also experiencing this crash.

Running:
Dank Null 1.7.89
p455w0rd's Library: v2.3.161

Crash Report:
https://paste.dimdev.org/ibupapusuq.mccrash

**Comment by p455w0rd** [comment]
#237
