### ISSUE TITLE
Glich With Dank Null and AE storage system

### ISSUE THREAD

**Issue by BioBird722** [p455w0rd/DankNull#244]
In my play threw of Enigmatica2Expert there is a bug that occurs when you place a DankNull in my AE storage. You can not get the item out unless you pull it out via ExprtBus with a DankNull and a fuzzy card for its filter. I just wanted to let you know. 

Love the mod keep up the good work.

**Comment by bloodscon** [comment]
Check item is in extract mod 
[https://github.com/p455w0rd/DankNull/issues/250]

**Comment by cjm721** [comment]
Fixed by #263
