### ISSUE TITLE
Out of Memory 

### ISSUE THREAD

**Issue by Ridous** [p455w0rd/DankNull#245]
https://paste.ee/p/5Wc1j

Also had to to toggle off The One Probe or I would have to crash upon looking at it

**Comment by p455w0rd** [comment]
You ran out of RAM. This is a limit of either your configuration or your hardware. Google "Minecraft Java args' to improve garbage collection and 'Minecraft Increase RAM' to increase allocated RAM. If you are hitting your max physical RAM limit, then the only option is more RAM. It just happened to be on my mod when it ran out.

**Comment by Ridous** [comment]
tried again after setting it to 12GBs and atleast I don't crash. But it hangs like crazy when looking at a specific null, all others are fine
