### ISSUE TITLE
Crash reports on FTB Revelations after trying to update.

### ISSUE THREAD

**Issue by Directhit124** [p455w0rd/DankNull#246]
I installed the latest versions of dank null then lib and it keeps crashing. I tried an earlier version, it let me get to the home screen then told me to update the lib to the latest one after I tried .160 instead of .161. I have crash report if you need it.

**Comment by d-avery** [comment]
I have the same issue, except that I didn't fiddle with earlier versions.

**Comment by Jugacu** [comment]
i've fixed it by updating WirelessCraftingTerminal, AE2WTLib and p455w0rdslib.

**Comment by d-avery** [comment]
> i've fixed it by updating WirelessCraftingTerminal, AE2WTLib and p455w0rdslib.

Thank you so much, that fixed it for me.
