### ISSUE TITLE
Fail to Rename Dank/Null using Anvil

### ISSUE THREAD

**Issue by Danekjovax** [p455w0rd/DankNull#247]
Dungeons Dragons & Space Shuttles 6.5
ForgeMultipart-1.12.2-2.6.2.83-universal
DankNull-1.12.2-1.6.80
p455w0rdslib-1.12.2-2.2.156

Thanks for this awesome mod, p455w0rd.  I love it so much, though I don't know why the dank nulls I use can't be name-customized.  I did see previous issues opened where you reported you were able to rename them, but I can't seem to do the same in the modpack I'm in.

Using "vanilla" mechanics, I attempt to rename a Mk V dank null (see screenshots).  After going through the motions, the dank/null is still named its original name.

Let me know if there's anything else you need to help troubleshoot.  Thanks again!
![DankNullRenameFail1](https://user-images.githubusercontent.com/10191173/71524330-14aac800-289b-11ea-8293-bdbd01533bd7.png)
![DankNullRenameFail2](https://user-images.githubusercontent.com/10191173/71524335-1aa0a900-289b-11ea-8e9f-77a196186b13.png)
![DankNullRenameFail3](https://user-images.githubusercontent.com/10191173/71524342-1e343000-289b-11ea-887e-ac95a065f677.png)

**Comment by cjm721** [comment]
Appears fixed by #263
