### ISSUE TITLE
DankNull ran into an issue

### ISSUE THREAD

**Issue by Wxrlds** [p455w0rd/DankNull#248]
Everytime I join our Server Vanilla Fix tells me DankNull runs into issues. Thought you might want to take a look at that.
Log (from Vanilla Fix): https://gist.github.com/Wxrlds/d30465da966009a2a1b1b5ae1f49d18e

**Comment by inspiiree** [comment]
Same issue here unfortunately for myself and a friend

**Comment by bloodscon** [comment]
check dank null has the correct dependencies for its version had similar report to this after i did an update to mod mode but forgot to update p455w0rd's Library

**Comment by inspiiree** [comment]
I actually updated the library too to latest dependacies and still no luck

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cjm721** [comment]
Duplicate of #237
