### ISSUE TITLE
1.11.2 all of the /dank/nulls don't have a texture

### ISSUE THREAD

**Issue by DireDiamond** [p455w0rd/DankNull#25]
OK so basically I made a mod pack for myself with a lot of mods and i noticed that the items don't have a texture. they work perfectly fine, have a shadow on the ground and everything, even when a block is selected it shows up just floating in the nothingness of my hotbar or on the ground.
![2017-11-24_01 15 34](https://user-images.githubusercontent.com/14033324/33191840-4d5e9be4-d0b5-11e7-8283-a2b092b41a5a.png)
![2017-11-24_01 15 43](https://user-images.githubusercontent.com/14033324/33191842-4d89f154-d0b5-11e7-845b-3d7662926188.png)

**Comment by LordRavenShadow** [comment]
i'm having the same issue in 1.12.2 All the mods modpack

**Comment by p455w0rd** [comment]
what version in 1.12? cuz it's working fine in DW20 1.12 and other packs that are in dev currently..could be a forge issue I guess..my local version is very different from what is public...lots of fixes..just some syncing kinks to work out

**Comment by LordRavenShadow** [comment]
sorry password ,
minecraft version :1.12.2 
minecraFT MOD pack : all the mode 3 
forge : 14.23.2555
thats is the issue that im haveing the mod in

**Comment by tipeon** [comment]
It seems to be an incompatibility with the [connected texture pack](https://minecraft.curseforge.com/projects/ctp).

Everything goes back to normal when I deactivate it.

**Comment by LordRavenShadow** [comment]
ok, so full story i installed optifine with  SONIC ETHER’S SHADERS and thats when i got the issue.  what i had to do, was uninstall optifine , reinstall the all the mods 3 . for the  textures show up so its not the mod, its optifine causing the issue. just a heads up on how i fix my issue.

sorry for the hassle 

minecraft version :1.12.2
minecraFT MOD pack : all the mode 3
forge : 14.23.2555

**Comment by p455w0rd** [comment]
yeah optifine i can do nothing about..I rly dunny why CTM would have anything to do with this..but simple solution is to just make my own textures..easy enough.,.consider it done ;) thanks for all the help everyone! :)

**Comment by LordRavenShadow** [comment]
hope it helps :)
