### ISSUE TITLE
Docking Stations going ham on NBT and RAM usage

### ISSUE THREAD

**Issue by Discomanco** [p455w0rd/DankNull#256]
We have run into some pretty serious issues. This is 2 different cases, that should probably be in 2 different issues, but both issues appeared on the same server, and the second one is rather short and possibly hard to replicate. Region Files for both issues can be supplied if desired
Modpack: Enigmatica 2 Expert v1.76b (MC 1.12.2)
Dedicated Server, 7GB RAM allocated
Versions used: DankNull 1.7.89, p455w0rdlib 2.3.161
Forge: .2847

Case 1, quite serious.
DankNull sitting in a Docking Station, that is connected to a Storage Bus (total of 6 Docking Stations on Storage Busses, only 1 had a DankNull in it). Server would freeze instantly the moment it was loaded and eventually crash from OutOfMemory (7GB). Before that chunk is loaded, server would usually sit at 2-3GB.
This DankNull had only been set up for a couple of hours before the server started crashing. It mainly caused an issue as a mob was walking into the affected chunk, briefly loading it.
![image](https://user-images.githubusercontent.com/4707702/73581332-1adb2800-4489-11ea-83c0-1d7b9355cd83.png)
Spark sampler reports:
Triggered by Animania Ewe's pathfinding
- https://sparkprofiler.github.io/#Qx1vpBem1u
- https://sparkprofiler.github.io/#h2z7K5MWJQ

https://sparkprofiler.github.io/#vMetXFP0li 
https://sparkprofiler.github.io/#KTJNtJqoOc (Triggered by DynMap)

Crash log: https://pastebin.com/Tiw9BjCW ("usual" OutOfMemery error I suppose)

Case 2, took a long time to apply:
A DankNull had been sitting in a Docking Station for a couple of weeks, not connected to anything, just used as a storage, ended up being a giant entity that would instantly freeze the server when loaded
![image](https://user-images.githubusercontent.com/4707702/73580789-2af20800-4487-11ea-85d9-2d43c7acc424.png)
Picture taken from NBTExplorer (frozen as I tried to expand OreDictModes)
Crash log: https://pastebin.com/Ef2c2HyG (again a "usual" OutOfMemory error)

**Comment by Chubblezap** [comment]
Had a similar issue that crashed my server the other day. Seems to only affect docked /dank/nulls.

**Comment by cjm721** [comment]
Should be fixed by #263
