### ISSUE TITLE
Custom sizes of /dank/null

### ISSUE THREAD

**Issue by ijo42** [p455w0rd/DankNull#258]
Mod is good but i want to see a configurable sizes _/dank/null_. Possible create in config field **Tier Slor multiplier**. As an option, this field will be multiplied by the _/dunk/null_ tier num and this number of slots in _/dunk/null_ of the current level will be.

**Comment by cjm721** [comment]
Actually going to close this. With how all the UI is setup having it dynamicly expand would be to complicated for the effort. Also dank bills already get pretty large and of start getting to much larger have to completely change how they store data.
