### ISSUE TITLE
[1.12.2] A lot of items/block not rendering in /dank/null

### ISSUE THREAD

**Issue by Morpheus1101** [p455w0rd/DankNull#26]
While holding the /dank/null in inventory an scrolling through the blocks, all i have show up except for marble form chisel which shows an empty /dank/null

![2017-11-24_21 32 06](https://user-images.githubusercontent.com/10524952/33208849-f1c621d0-d15e-11e7-8fc0-9721b52d3264.png)

**Comment by p455w0rd** [comment]
yeah the rendering is failing for a lot of stuff..I'll look into it..I have till Sunday to get a new build out for DW20 1.12 pack..will try and figure this out before then

**Comment by Morpheus1101** [comment]
okies thanks, always great to see a modder thats so eager and quick to respond to bug reports.  More ppl should patreon ya for that alone :D

**Comment by p455w0rd** [comment]
yeah there's a major desync going on..gotta find it..it's not specific to the block/item, but more that the inventory is properly being synced..yay

**Comment by p455w0rd** [comment]
wasn't a desync :)
