### ISSUE TITLE
DankNull-1.12.2-1.6.77.jar item duplication 

### ISSUE THREAD

**Issue by Kadwen01** [p455w0rd/DankNull#260]
Just started to play the FTB Revelation pack and was using the dank null for mining when i noticed this duplication bug.

So far was able to replicate with any stack able item in the game.

I only noticed this on the Emerald level of the dank null have not tested on lower levels.

its not a fast dupe but its a dup none the less...

Steps to replicate.
-Have a stack of 3 items in any dank null slot
-right click to take half a stack out.   you end up with 2 item on your cursor and 2 in the slot.  
-put 1 item into your player inventory and put 1 back into the dank null and you are back to 3.
-repeat

**Comment by Yee1er1** [comment]
I followed the steps on a singleplayer mode in FTB Revelations and it worked.
I followed the steps with the /Dank/Null mod by itself in a singleplayer world with the latest version it did not work. Possibly, the modpack you are using has the mod outdated for its version.

Nonetheless, great discovery!

**Comment by cjm721** [comment]
Outdated version and very similar issues fixed in #263 Open new bug using version past that if still persists.
