### ISSUE TITLE
Renamed DankNull reverts to original name on item pickup/place

### ISSUE THREAD

**Issue by PhilGooodInc** [p455w0rd/DankNull#264]
I am playing on MC Eternal pack 1.3.4

p455w0rdslib-1.12.2-2.3.161
DankNull-1.12.2-1.7.89.jar

the MK VI dank CAN be renamed, but loses the name as soon as item is picked up or placed. Gets annoying when trying to get items out not knowing which one is which. (i have 3)

Maybe a native way to visually differentiate if this cant be avoided?

**Comment by JohnTitor95** [comment]
Same issue here, i am trying to keep one for mob drops, one for generic blocks and another for ores. However, each one's names get reverted upon using. Would be really nice to be able to keep name changes.

**Comment by Twisted-Code** [comment]
can confirm this happens. I thought this was supposed to be fixed a few builds ago? 😞

**Comment by cjm721** [comment]
Fixed by #263
