### ISSUE TITLE
tried updating /dank/nulls on ftb revelations

### ISSUE THREAD

**Issue by StarBanger69** [p455w0rd/DankNull#267]
I tried to update my /dank/nulls version on ftb revelations, also updated passwords library, but now every time i try to load it it crashes. Halp!
[crash-2020-03-28_19.51.31-client.txt](https://github.com/p455w0rd/DankNull/files/4398086/crash-2020-03-28_19.51.31-client.txt)

**Comment by cjm721** [comment]
Not a dank null issues its an issue with [ae2wtlib](https://github.com/p455w0rd/AE2WirelessTerminalLibrary)
