### ISSUE TITLE
Broken pumping of items

### ISSUE THREAD

**Issue by ghost** [p455w0rd/DankNull#269]
Connected an item conduit to a docked dank null. when you hover over it, hwyla says the correct number of blocks being pumped to it but when you open it's GUI the number of items resets back to 0 every time. Tried it with item conduit from enderio and item extraction cable from cyclic. Both have the same issue.

**Comment by cjm721** [comment]
Please add what DankNull version you are using, If it is not at least 1.7.90, update.
