### ISSUE TITLE
Items disappearing entirely

### ISSUE THREAD

**Issue by ghost** [p455w0rd/DankNull#270]
Version: 1.7.9.1
Latest forge 1.12.2
Description: Blocks disappear from inside the dank null when entire stacks are placed inside with a shift click. If you press on the slot of that item it will extract a stack as if the items were there but there is no icon nor amount shown. If you place another type of block after it will disappear as it will try to fill the "empty" slot but of course it's not an empty slot as there are technically blocks still there. 

Methods to recreate: grab any dank null and shift click multiple stacks of items in. Press escape and reopen the gui. Added blocks will not be shown but if you press on the slot they should be in you will get the items back.

It was working fine in 1.7.9.0

EDIT: it's the same with importing items into the dank null like if you connect a conduit, extraction cable etc. Same thing happens the docking station says the correct count of blocks but when the gui is opened no items are shown

**Comment by robobeaver6** [comment]
I am getting the same problem.  Not just when I add a complete stack, but also as I am mining.  If I count the stone mined, and look back in the /dank/null after I have mind a load, either some or all is missing.  I have just been mining for an hour, and I have 88 cobble.  That is definitely not right.
/dank/null version DankNull-1.12-1.4.46.jar

I am running the 1.12.2 Direwolf20 mod pack, on a server with only a couple of extra mods:
veinminer
forge essentials
worldedit

Server is running on Ubuntu18.04
Desktop Windows 10

**Comment by ghost** [comment]
> I am getting the same problem. Not just when I add a complete stack, but also as I am mining. If I count the stone mined, and look back in the /dank/null after I have mind a load, either some or all is missing. I have just been mining for an hour, and I have 88 cobble. That is definitely not right.
> /dank/null version DankNull-1.12-1.4.46.jar
> 
> I am running the 1.12.2 Direwolf20 mod pack, on a server with only a couple of extra mods:
> veinminer
> forge essentials
> worldedit
> 
> Server is running on Ubuntu18.04
> Desktop Windows 10
Bro your 50 versions away update and se

> I am getting the same problem. Not just when I add a complete stack, but also as I am mining. If I count the stone mined, and look back in the /dank/null after I have mind a load, either some or all is missing. I have just been mining for an hour, and I have 88 cobble. That is definitely not right.
> /dank/null version DankNull-1.12-1.4.46.jar
> 
> I am running the 1.12.2 Direwolf20 mod pack, on a server with only a couple of extra mods:
> veinminer
> forge essentials
> worldedit
> 
> Server is running on Ubuntu18.04
> Desktop Windows 10

Your like 50 versions away tho 🤔

**Comment by robobeaver6** [comment]
That was the version that was distributed with the official FTB mod pack.  I have manually upgraded to DankNull-1.12.2-1.7.91.jar and p455w0rdslib-1.12.2-2.3.161.jar and the behaviour is the same

**Comment by ghost** [comment]
> That was the version that was distributed with the official FTB mod pack. I have manually upgraded to DankNull-1.12.2-1.7.91.jar and p455w0rdslib-1.12.2-2.3.161.jar and the behaviour is the same

Ok well that confirms my issue then ok no worries I just hope it'll get fixed soon enough need to finish a massive base

**Comment by robobeaver6** [comment]
It seems to be OK up to 127 items.  as soon as it hits 128 it goes invisible.  If it is the last thing in the list, you can still pick it back out of the Dank inventory, but if it is not, everything else shuffles up and overwrites it.

**Comment by ghost** [comment]
> It seems to be OK up to 127 items. as soon as it hits 128 it goes invisible. If it is the last thing in the list, you can still pick it back out of the Dank inventory, but if it is not, everything else shuffles up and overwrites it.

Ye exactly the same thing here like it's useable for now if I wanted one block but then just loses its purpose

**Comment by kreezxil** [comment]
I had a player just have this issue, I'm sure  many more will be coming along afterwards. See my own link above for the deets on that.

**Comment by moonheart08** [comment]
I've had the issue myself. I'll put my golden /dank/null's NBT here in a bit (thanks Integrated Dynamics)
