### ISSUE TITLE
[Interaction] Placing Angel Block from Extra Utilities 2 mod causes the /dank/null to disappear

### ISSUE THREAD

**Issue by snowfiend** [p455w0rd/DankNull#271]
Version: 1.12.2-1.7.89
Modpack: Enigmatica 2: Expert
To recreate: Place an Angel Block from the Extra Utilities 2 mod into a /dank/null/, then select the block from the GUI. Right click to place the Angel Block into the world. Block is placed and the /dank/null is removed from the player's inventory along with its contents.

**Comment by cjm721** [comment]
Update to 1.7.90 or further
