### ISSUE TITLE
DankNull crashing when selecting active slot.

### ISSUE THREAD

**Issue by Haanicz** [p455w0rd/DankNull#272]
Dank null crashes with message 
`java.lang.NoSuchMethodError: p455w0rdslib.util.ItemUtils.areItemsEqual(Lnet/minecraft/item/ItemStack;Lnet/minecraft/item/ItemStack;)Z` 
when alt-clicking a slot to select it.

Crash log: https://pastebin.com/tBeMhTKp

**Comment by cjm721** [comment]
Re-produce on latest version and then open new bug if you can re-produce.

**Comment by vpArth** [comment]
Isn't p455w0rdslib-1.12.2-2.3.161.jar and danknull-1_12-1_4_46.jar considered as new? What is «new» then?

Upd: found `/dank/null 1.7.91` release. Crash is not reproduced, but all item counts are now broken.
May be it would be nice to add mod/core versions compatibility checking.
