### ISSUE TITLE
Does not take items and forgot which item slots are used

### ISSUE THREAD

**Issue by Rinma** [p455w0rd/DankNull#273]
After the last update everything is broken. I only see a small amount of the items inside my danknull and a lot of them are invisible. New blocks are not taken in and land in my inventory.

I updated from 1.12.2-1.7.89.

Version: 1.12.2-1.7.92
Forge: 14.23.5.2847

**Comment by cjm721** [comment]
Only able to reproduce new items not taken in, of which its only items not in first slot.
