### ISSUE TITLE
Dank Nulls dupe items

### ISSUE THREAD

**Issue by SubtleSloth** [p455w0rd/DankNull#275]
Just discovered this issue on our E2E server this morning. Posted it to E2E as well.

https://github.com/NillerMedDild/Enigmatica2Expert/issues/1643

**Comment by cjm721** [comment]
This is only reproduce-able on server.

**Comment by SubtleSloth** [comment]
@cjm721 I didn’t even think to try it out in SP, thanks for the heads up!

**Comment by cjm721** [comment]
What version of dank null was this on. I know it's affecting head but I don't believe it affects current release build.

**Comment by SubtleSloth** [comment]
@cjm721 i believe it’s DankNull-1.12.2-1.7.90.jar. It’s the version that is currently used in Enigmatica 2: Expert.

**Comment by SubtleSloth** [comment]
@cjm721 i believe it’s DankNull-1.12.2-1.7.90.jar. It’s the version that is currently used in Enigmatica 2: Expert.

**Comment by cjm721** [comment]
Please confirm the version if you are not sure

**Comment by SubtleSloth** [comment]
> Please confirm the version if you are not sure

I got that version number from the modpack version I’m currently using. So that’s gotta be the one right?
