### ISSUE TITLE
Dank null still items disappearing

### ISSUE THREAD

**Issue by ghost** [p455w0rd/DankNull#276]
Description: Same as issue #270. When you put more than 127 items in the dank null the item's icon and number disappears but if you click on the slot it was in it gives you the items back as if they are still there.
Also its game breaking if you put a different block in after that it will put it in the slot that the first blocks disappeared in thinking it's empty. When you then click on this newly added blocks it deletes the block entirely and gives you the old blocks that disappeared back
Steps: get a dank null and put more than 127 of any block inside
Version: 1.7.94

**Comment by cjm721** [comment]
Unable to reproduce on v94 SP. Test with just dank null and if you can still do it will start looking at other environmental differences.

![image](https://user-images.githubusercontent.com/2738614/79175316-409e7a80-7db2-11ea-81cc-27df890c965e.png)
![image](https://user-images.githubusercontent.com/2738614/79175326-45fbc500-7db2-11ea-8c3b-b495564bbec7.png)

**Comment by cjm721** [comment]
Something similar to this happens when on servers only and is reported in #275
