### ISSUE TITLE
[Feature Request] Integration with Refined Storage

### ISSUE THREAD

**Issue by llloyd4** [p455w0rd/DankNull#277]
So. I was hoping maybe you could integrate this with Refined Storage, specifically the External Storage bus. So I could drop my Dank/Null into it's dock and have access to the cobble / dirt for crafting / autocrafting without having to empty it into external storage (like drawers). Be one less step, just come home, drop it into it's dock and it becomes a multi slot drawer with all the cobble / dirt / netherack / sand / gravel in it available to RS to use in auto crafting.

**Comment by cjm721** [comment]
Update your build. It is already compatible.
