### ISSUE TITLE
FTB DIREWOLF 1.12.2 - Duplication Bug

### ISSUE THREAD

**Issue by AlbertoCastel** [p455w0rd/DankNull#28]
I found a duplication bug, when you use /dank/null with only one item in it and you start using this item it starts to duplicate without having more in /dank /null.

**Comment by p455w0rd** [comment]
are you in creative? it may very well just be the changes i've made locally for the next update as I've changed syncing a bit, but I just tested and I'm not experiencing this with my in dev build..just tryin to rule out possibilities

**Comment by AlbertoCastel** [comment]
I'm on a server, look 
https://imgur.com/ybWt1kf

**Comment by Diablofan** [comment]
I just was able to trigger this as well, in a survival world on a server.

Steps to Reproduce:

1. Obtain Solidified Experience from Actually Additions
1. Place in a /dank/null
1. Select said Solidified Experience
1. Right Click several times
1. ???
1. Profit from infinite experience.

**Comment by Tuvermage** [comment]
Works most blocks and doesn't have to be the only item. Just has to be the selected item. Was able to dup environment tech crystals and awaken draconium.

**Comment by p455w0rd** [comment]
ok so just tested in locally in dev env and I am unable to reproduce with items nor blocks..with 3 reports this is definitely a bug in the current public version, but I have made a ton of changes to the in dev version, so it was likely fixed along the way..I've done a lot of updating to packet handling and related stuff so it was likely resolved there..I will mark this issue as fixed, but will leave it open until after the next release in case it comes back...if it is still an issue after that, it boils down to mod interaction..thanks for all the reports!
