### ISSUE TITLE
Items not showing up in UI

### ISSUE THREAD

**Issue by DoctahSawbones** [p455w0rd/DankNull#280]
The items are in the null, and you can pull them out, but they aren't visible.
![2020-04-15_20 06 00](https://user-images.githubusercontent.com/44814348/79412842-a4b47080-7f63-11ea-92c5-3d6b08720a50.png)

This first image is of me putting in some netherbrick.
![2020-04-15_21 47 07](https://user-images.githubusercontent.com/44814348/79412730-6dde5a80-7f63-11ea-8e66-2e4f0eff83ef.png)

This image is from three seconds later, after I closed and reopened the null. You can see in my hotbar that the netherbrick is in the null, but it's not visible in the UI.
![2020-04-15_21 47 10](https://user-images.githubusercontent.com/44814348/79412754-7f276700-7f63-11ea-92cb-aa4a052d505d.png)

Another issue I noticed is that OreDictionary wasn't functional for logWood, but it's possible that's a feature and I didn't realize it.

**Comment by cjm721** [comment]
Please keep it as one bug per issue.

Need to know which Dank Null version you are on.

**Comment by DoctahSawbones** [comment]
Alright. I am on version 1.7.94
A little more messing around, and the issue only seems to occur while connected to a server. Being more specific, the items only disappear from the UI when there is more than 127 of them.

**Comment by LordPieYT** [comment]
> Alright. I am on version 1.7.94
> A little more messing around, and the issue only seems to occur while connected to a server. Being more specific, the items only disappear from the UI when there is more than 127 of them.

Yeah, I'm getting the exact same issue. Same version too, plus 1.12.2-14.23.5.2847. 128 blocks and above breaks the rendering. 

It's also interesting to note that the Dank Null *seems* to think that a blank-rendered item is an unoccupied slot. So it's possible to place an item in the blank spot where a block should be rendered. After closing and re-opening the Dank Null, the new item is in the correct spot, though.

@DoctahSawbones: Could you share your mod list just to see if we have a mod in common? Might at least help us determine if it's another mod interfering, at the very least.

My mod list's [here](https://gist.github.com/alandavison/280d1054b20bf8bd106b817f86a6cd27).

**Comment by cjm721** [comment]
Don't need mod list. Can replicate when only dank null is installed. More wondering if this ever worked on older versions.

**Comment by NotOats** [comment]
> Being more specific, the items only disappear from the UI when there is more than 127 of them.

It doesn't just disappear if it's just over 127 items. I have a stack of 292 stone that shows as 36 items. It seems like some stack counting mechanism is broken. Also on version 1.7.94
