### ISSUE TITLE
update removed all items from dank null...

### ISSUE THREAD

**Issue by CurlyFlow** [p455w0rd/DankNull#285]
Dank Null Version: 1.12.2 1795
p455w0rds Lib Version: 1.12.2 23161
Forge Version: 14.23.5 2854

Steps To Reproduce:
1. install dank null 1791
2. update to 1795
3. all items in dank null lost (latest tier) (was in hotbar)

Was this tested on Single Player or Server (or Both)?
This was a singleplayer world which got ported to multiplayer. (I dont know if that matters tho) First dank null was build in multiplayer tho.

So this whole odysee startet when i first used your mod (latest version), it wasnt voiding items, so i installed the old version 1791, in which the voids worked.

Today i upgraded my dank null to the latest tier... and then the next bug happend, i couldnt see what i have in it (the slots), like it display another block and i click on e.g. cobbelstone, but i get diamands... 

Thats what i thought okay lets upgrade to latest version, even if it doesnt void, bc in the latest tier dank null you dont really need void... installed update and all items are lost... :) Its not a big thing, but i thought i report it.

Didnt changed any other mod / version / forge, really just upgraded onyl your mod and did a restart.

**Comment by cjm721** [comment]
Please read the change log. This was mentioned.

**Comment by thelapisfox** [comment]
Just a suggestion but perhaps you should put this warning/change log also on your CurseForge page since most people download from there or the Twitch app and only come here after an issue occurs.
