### ISSUE TITLE
Why not extract ALL items when docked? :)

### ISSUE THREAD

**Issue by CurlyFlow** [p455w0rd/DankNull#286]
Hi, thanks for the fast help in my last issue.

Would it be possible to have a new mode while docking the danknull which extracts all items (or lets say, extract all items how its configured, every single slot? Like cobble till 64, stone till 1, (how ever you configured it)?

Maybe a Box [ X ] at the top of the dank null like 

[ X ] When docked, extract all slots

**Comment by cjm721** [comment]
This is already taken care of by the per stack settings. Do not see the need to add a overarching overriding one as it be confusing for users.

**Comment by CurlyFlow** [comment]
Please explain. My mother language is not english.
As far as i see the only way to do it at the moment is to manually selecting every slot and wait till every slot is imported?

Edit:
sorry i think that was again a mistake by me, it seems like it wasnt properly connected, now its also importing from non selected slots, like what i suggested.. xD I thought it will only extract the item selected (with red)
