### ISSUE TITLE
If set to extraction NO, you cant place blocks

### ISSUE THREAD

**Issue by CurlyFlow** [p455w0rd/DankNull#287]
Dank Null Version: 1.12.2 1796
p455w0rds Lib Version: 1.12.2 23161
Forge Version: 14.23.5 2854

Steps To Reproduce:
1. Set e.g. cobblestone to "place all but 1" and "do not extract"
2. mark it with red (alt click)
3. you cant place cobblestone, if set back to extract till 1 or 16 or 64 you can place again..

Was this tested on Single Player or Server (or Both)?
Server

**Comment by cjm721** [comment]
That is intended. Placement is a form of extraction. May rework wording but I already changed the default to extract all but 1 in the next update.

**Comment by CurlyFlow** [comment]
Sorry, that makes no sense, why have an option which says "place all but 1", which doesnt affect anything?

1.) If you place something it should handle it like its settings under "place all but 1"
2.) If you extract somethingit should handle it like its settings under "do not extract"
