### ISSUE TITLE
Duplication glitch

### ISSUE THREAD

**Issue by Waxyy** [p455w0rd/DankNull#289]
Very easy and game-breaking duplacation glitch.

Step 1 : Put the item/block in the /dank/null/.
Step 2 : Drop and open the /dank/null/ simultaneously.
Step 3 : The GUI will open and take the item/block you put before.
Step 4 : Pick up the /dank/null/, open it and the item you put before will still be here.

It's not a graphic bug.

Video of the glitch : https://gyazo.com/816578e87381b0e6bd91b0ebbff907eb

**Comment by cjm721** [comment]
Follow the template please. Going to assume you are on an old version and close the bug.
