### ISSUE TITLE
DW20 1.12: /dank/null/ + Fluid Buckets = Bugs

### ISSUE THREAD

**Issue by ConnorMiner** [p455w0rd/DankNull#29]
I ran into issues with putting buckets with fluids in them into the /dank/null/. 

1. The fluids place above the block you right-click on (or one block above the expected placement spot if there is a block there).
2. The buckets aren't affected in any way, leaving the fluids in them when you use them.

How to Reproduce:

1. Put buckets with fluids in them into a /dank/null/.
2. Use them, and observe the issues mentioned above.

I was in Survival when I encountered these issues, in case you were going to ask.

**Comment by p455w0rd** [comment]
This was a WIP feature that I thought I had disabled lol..I'll get it fixed in next update

**Comment by p455w0rd** [comment]
so it is still disabled..but only vanilla buckets..i'm pretty sure the issue you're experiencing is due to the bucket being a forge bucket aka the `Universal Bucket`..fixed in dev..thanks for the report :)
