### ISSUE TITLE
Unable to change extraction mode

### ISSUE THREAD

**Issue by McGladiator** [p455w0rd/DankNull#292]
Dank Null Version:1.7.96
p455w0rds Lib Version:2.3.161
Forge Version:14.23.5.2838

Steps To Reproduce:
1.Installed danknull 1.7.96 and p455w0rdslib 2.3.161
2.started world got danknull put items in
3.tried ctrl+left click and extraction mode stayed on do not extract

Was this tested on Single Player or Server (or Both)?
Single Player

**Comment by cjm721** [comment]
Unable to replicate on either forge 2768 or 2854 with just dank null + a few of my other testing mods installed.
