### ISSUE TITLE
Please change the default extraction mode.

### ISSUE THREAD

**Issue by TheSaucyWelshman** [p455w0rd/DankNull#293]
I originally wrote this as a bug report but I'm not 100% sure it's a bug.

Dank Null Version:1.7.96
p455w0rds Lib Version:2.3.161
Forge Version:14.23.5.284

Steps To Reproduce:
1. Make a dank null
2. try to place block with dank null
3. fail

Was this tested on Single Player or Server (or Both)?
SSP with only JEI, /dank/null, p455w0rdlib, TOP

The default extraction mode is set to none so you need to change it for every slot to be able to place that block. It would be nice if the default extraction mode was either `all` or `all but 1`.

**Comment by cjm721** [comment]
b2732109aea467a35d10cba406d631fe55bc0d6b

**Comment by cjm721** [comment]
Already did this earlier in the week. Have not pushed a new release yet.

**Comment by billybricker** [comment]
Holy shit that was fast. Thank you!

**Comment by TheSaucyWelshman** [comment]
Ah, guess I should have checked the commits. Any way thanks for the super fast response!
