### ISSUE TITLE
Items showing up incorrectly, but withdrawing properly

### ISSUE THREAD

**Issue by Fevix** [p455w0rd/DankNull#296]
Dank Null Version: 1.7.91
p455w0rds Lib Version: 2.3.161
Forge Version: 14.23.5.2847

Steps To Reproduce:
1. Put items in
2. Shift+Right click to view inventory
3. First stack shows up twice in inventory, other stacks shifted until it randomly corrects itself.

Was this tested on Single Player or Server (or Both)? Server (Privately hosted)

**Comment by cjm721** [comment]
Current Latest version is 96, must reproduce on that version for me to investigate.

**Comment by Fevix** [comment]
Certain was downloaded two days ago from curseforge, where is newest
version available?
