### ISSUE TITLE
Cannot change extraction mode

### ISSUE THREAD

**Issue by OttoMaster** [p455w0rd/DankNull#298]
Dank Null Version: DankNull-1.12.2-1.7.97.jar
p455w0rds Lib Version: p455w0rdslib-1.12.2-2.3.161.jar
Forge Version: forge-14.23.5.2838

Steps To Reproduce:
1. Insert items into dank null
2. Try to pull said items out
3. Leaves 1 item behind
4. Try to use CTRL + Click to change extraction to EXTRACT ALL
5. Extraction mode does not change

Was this tested on Single Player or Server (or Both)?
Server

**Comment by cjm721** [comment]
Unable to reproduce with just dank null install. Assume there is some mod conflict (on list to make those keybinds actual keybinds so they can be changed).

**Comment by JBSTheGamer** [comment]
> Unable to reproduce with just dank null install. Assume there is some mod conflict (on list to make those keybinds actual keybinds so they can be changed).

I am having the same issue, I know this issue is old. I can't seem to figure out what is causing it.
