### ISSUE TITLE
DIREWOLF 1.12 placement issue

### ISSUE THREAD

**Issue by Nbenito** [p455w0rd/DankNull#30]
Video of issue found here: https://youtu.be/wIs2npQ4bsc

The issue i am having with the /Dank/Null is that i cant seem to place any blocks at all using it. no matter what i use. i have tried different versions of the modpack and also different versions of the mod itself. Description and video explains bit more detail

**Comment by Gravlok** [comment]
I have the exact same issue. It was working fine prior to pack update to 1.2.0 (version of mod 1.0.13 -> 1.0.14). Now it doesn't work regardless is it a new one or upgraded.

**Comment by p455w0rd** [comment]
can one of you hop on my discord pls? I'll throw you and in-dev build..i just want to test that this functionality is fixed - http://p455w0rd.net/discord

**Comment by Nbenito** [comment]
Sory, wasnt able to be online to use that link in time.

**Comment by p455w0rd** [comment]
ok..so we've figure it out! this is due to FTBUtils disabling FakePlayers placing blocks..enable and you should be set :)

**Comment by p455w0rd** [comment]
ok..so this is likely due to FTBUtils disabling placing/breaking blocks from fake players..this should be resolved in the coming update :)
