### ISSUE TITLE
The Disallow Insertion config option has no effect

### ISSUE THREAD

**Issue by pcd1193182** [p455w0rd/DankNull#300]
Dank Null Version: 1.12
p455w0rds Lib Version: ?
Forge Version: ?

Steps To Reproduce:
1. Install Enigmatica 2: Expert
2. Enter creative
3. Create a /dank/null docking station and put a /dank/null in it
4. Use item pipes to insert items

Was this tested on Single Player or Server (or Both)?
Single Player

Was this tested with just Dank Null installed?
No

From code inspection, it looks like the Options.allowDockInserting variable is set but never used.

**Comment by cjm721** [comment]
I intentionally got rid of that support, just have not cleared out the config yet.
