### ISSUE TITLE
[FR]Adding a config setting to allow writing

### ISSUE THREAD

**Issue by ChromaPIE** [p455w0rd/DankNull#302]
Firstly, I know it's very OP but modpackers will have it changed somehow.

When I put danknull in a shipping container from BDS&M, install a piece of ME Storage Bus and opened the Terminal, I sadly realized that the danknull inside the container is read-only. Could you please add a setting to allow writing into it? It could be disabled by default and allows to be manually enabled.

**Comment by cjm721** [comment]
This was already a config option in older versions. Latest has it always enabled.
