### ISSUE TITLE
Items Being Completely Deleted

### ISSUE THREAD

**Issue by thelapisfox** [p455w0rd/DankNull#304]
Dank Null Version: DankNull-1.12.2-1.7.100.jar
p455w0rds Lib Version: p455w0rdslib-1.12.2-2.3.161.jar
Forge Version: forge-14.23.5.2847
Mod Pack: MC Eternal 1.3.5b

Steps To Reproduce:
(Not sure what happened so not sure how to reproduce it. Below are the only steps I can think of.)
1. Make some Blocks of Quartz
2. Add them to Dank Null
3. Some time later, see empty spots where they use to be (completely gone, not just blank like the over 127 bug).

Was this tested on Single Player or Server (or Both)?
Single Player open to LAN

Was this tested with just Dank Null installed?
No.

Was playing the game and had made about 6 stacks of Nether Quartz blocks and put them into the /dank/null in order to make room in my inventory. Forgot about them until I needed them about a day later. Noticed 2 empty spots in my /dank/null. I know one was the Quartz blocks, don't remember what they other one was. It wouldn't let me select those spots nor could I mouse wheel to them (would skip over them). I was even able to add new blocks to those spots without issue. This means that 2 different items were just randomly and completely deleted from the /dank/null. If it helps any, this was slots 1 & 2 of the third row in a MK IV.

**Comment by cjm721** [comment]
Guessing you updated in-between those two events. Changelog mentions that dank nulls will be reset on update from <95 to >95.

**Comment by thelapisfox** [comment]
@cjm721 You closed this prematurely. I searched the issues before posting regarding that. No, this was NOT due to updating. I request it to be reopened.

**Comment by cjm721** [comment]
> Forgot about them until I needed them about a day later.

Is not reproduction steps I will take. If you can cause it to happen again sure, but with the information you provided I will not be looking into it.

**Comment by thelapisfox** [comment]
So be it since I've gone back to the older version any further eval on my part is impossible, specially since I'm not sure when or how the items disappeared.

Just know that you have a bug in your coding somewhere that you are ignoring.

**Comment by cjm721** [comment]
There are many bugs, I prioritize the ones that are reproducible.

**Comment by MegaByte-MB** [comment]
duh.

**Comment by Paddy69** [comment]
something similar happened to me not to long ago, except the entire dank null disappeared from my inventory all together, it was the same verstion of forge dank null and the LIB

**Comment by sqikerz** [comment]
Same thing happened to me, had 1000 sky stone and 30 gold ore in my dank null (tier 5)  and those completely disappeared over time (I noticed when I went /home)


I had other things in the dank null, but only some stuff disappears.
Also cobblestone randomly disappears and it’s a pain since I need building blocks but I can’t have 6000 cobblestone in my inventory.
