### ISSUE TITLE
Unable to un dock/take out the dank null from docking station MC V 1.12.2

### ISSUE THREAD

**Issue by Paddy69** [p455w0rd/DankNull#305]
Dank Null Version: 1.7.1000
p455w0rds Lib Version:2.3.161
Forge Version:14.23.5.2847

Steps To Reproduce:
1. place dank null in docking station
2. shift right click to take out
3. does not come out of docking station
4. make this report

Was this tested on Single Player or Server (or Both)?
server
Was this tested with just Dank Null installed?
no

**Comment by Paddy69** [comment]
![Screen Shot 2020-05-16 at 12 12 00 PM](https://user-images.githubusercontent.com/63801613/82124647-7ac2b980-976e-11ea-9cba-6c71b6218e2e.png)
when trying to syphon items out if the dock it showed the entire stack of cobble stone in the dank null in the first inventory slot of my inv for 3 seconds and then it deleted the item that was in that slot (my pickaxe)

**Comment by cjm721** [comment]
Unable to re-produce with just dank null installed. If you find what mod it is conflicting with can create new issue.

Also only post one bug per issue ticket. Second one not nearly enough information to determine what you did.

**Comment by Ethernaloos** [comment]
Try un-equipping your shield when shift-right clicking lol

**Comment by TheMeq** [comment]
> Try un-equipping your shield when shift-right clicking lol

This resolves the issue, unequipping the shield allows you to remove the dank null.

**Comment by TronWoWGamer** [comment]
Also had the same problem.  Resolved when removing torches from off hand, so I expect it is the same with whatever you are holding in the offhand.
