### ISSUE TITLE
unable to take dank null out of docking station

### ISSUE THREAD

**Issue by Paddy69** [p455w0rd/DankNull#306]
Dank Null Version: 1.7.1000
p455w0rds Lib Version:2.3.161
Forge Version:14.23.5.2847

Steps To Reproduce:
1.place dank null in dock
2.shift right click to take out
3.does not come out

Was this tested on Single Player or Server (or Both)?
on server
Was this tested with just Dank Null installed?
no mod list-> https://github.com/god-ferny/summit-pack

**Comment by cjm721** [comment]
That pack is not in a form I will support. If you find the mods Dank-Null conflicts with report that, not an entire pack where I would need to go through it all to filter.

Also dank null version 1000 does not exist. Ignored it in the first report but this is your 3rd time.

**Comment by Paddy69** [comment]
![Screen Shot 2020-05-18 at 8 31 59 AM](https://user-images.githubusercontent.com/63801613/82213405-14f73e80-98e2-11ea-8276-2bd3f203415b.png)
