### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by chrisa64** [p455w0rd/DankNull#309]
Playing in PO3, and whenever I try to craft the dank null mk VI, it causes game to become unresponsive. Only way to exit is ALT-F4 or end task in task manager. I have checked the crash report folder but no report is made. Does anybody else have this issue?

**Comment by cjm721** [comment]
Unable to reproduce.

Also please follow the bug template when reporting bugs.

**Comment by chrisa64** [comment]
Cool thanks for the great help and closing this immediately! 👍
