### ISSUE TITLE
Duplication Glitch 

### ISSUE THREAD

**Issue by Osprey4444** [p455w0rd/DankNull#312]
**Dank Null Version:** 1.12.2-1.7.94
**p455w0rds Lib Version**: 1.12.2-2.3.161
**Forge Version:** 14.23.5.2847

**Steps To Reproduce:**
1. Put Dank Null with Items in on Docking Station
2. Take items from Dank Null whilst it is in docking station
3. Remove Dank Null from docking station
4. Place Dank Null back on docking station
5. Break Docking Station
6. Replace Docking Station
7. Docking Station will have the dank null with the items you just removed
8. ???? literal profit.

**Was this tested on Single Player or Server (or Both)**? Both

**Was this tested with just Dank Null installed, if not what is the minimal set of mods to cause the issue?** No, it was tested on FTB Stoneblock 2 version 1.17.0

**Comment by cjm721** [comment]
Update to latest dank null (currently 101)
