### ISSUE TITLE
Dupe items

### ISSUE THREAD

**Issue by Wolfrunn3r** [p455w0rd/DankNull#313]
Dank Null Version: 1.12.2-1.7.90
p455w0rds Lib Version:
Forge Version:

Steps To Reproduce:
1.place on dock 
2.remove item in first slot
3.replace dank null on dock and remove again.

Was this tested on Single Player or Server (or Both)?  Single player

Was this tested with just Dank Null installed, if not what is the minimal set of mods to cause the issue?  Was found while using MCternal mod pack only works with 1 item stack in the dank null.

**Comment by cjm721** [comment]
Your 11 versions out of date, please update.
