### ISSUE TITLE
Dank Null's Seem To Be Broken On My Server.

### ISSUE THREAD

**Issue by pixelblob** [p455w0rd/DankNull#314]
Dank Null Version:1.4.101
p455w0rds Lib Version:2.3.161
Forge Version:14.23.5.2847

Steps To Reproduce:
1.Be on my server. po3pixel.ddns.net
2.Have the Space Odyssey Pack.
3.Use a dank null.
4.Fill up the dank null 20 slots or so
5.One or two items then might turn invisible in the dank null.
6.The items will then overlay with each other.

Was this tested on Single Player or Server (or Both)?
Both

Was this tested with just Dank Null installed, if not what is the minimal set of mods to cause the issue? Yes it was.

**Comment by cjm721** [comment]
You mention it was tested on both server and single player, and with just dank null installed but steps to reproduce have it on a specific server with many mods.

Tested on singleplayer and server with just Dank Null installed and was unable to reproduce.

**Comment by pixelblob** [comment]
Server mod list:
![image](https://user-images.githubusercontent.com/34137159/83977358-4b801200-a900-11ea-801f-501b17c38a00.png)

My mod list:
![image](https://user-images.githubusercontent.com/34137159/83977389-85511880-a900-11ea-9854-d2d635897b40.png)

Another Photo:
![image](https://user-images.githubusercontent.com/34137159/83977413-aca7e580-a900-11ea-9bba-b530a7136f00.png)

Gif:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34137159/83977600-0066fe80-a902-11ea-8fa5-bc840f928970.gif)

**Comment by cjm721** [comment]
Your gif does not match your reproduction steps.

**Comment by cjm721** [comment]
Unable to reproduce with Gif. Then noticed you aren't on version 101 you are on 91. 

Update.
