### ISSUE TITLE
Dupe Glitch

### ISSUE THREAD

**Issue by DrewSin-4** [p455w0rd/DankNull#316]
Dank Null Version:  1.7.90
p455w0rds Lib Version: 2.3.161
Forge Version: 14.23.5.2847 (1.12.2)

Steps To Reproduce:
1. Place an item in the dank null and take the item out.
2. Drop the Dank Null or Die
3. The item will end up being copied within the Dank Null whilst also remaining in your inventory.

Was this tested on Single Player or Server (or Both)? Both

Was this tested with just Dank Null installed, if not what is the minimal set of mods to cause the issue? Only tested in a Modpack. MC.Eternal.

**Comment by cjm721** [comment]
You are 11 versions out of date.
