### ISSUE TITLE
Not able to open Dank Null while the player is partially or completely above air (flying or standing on the edge of a block) 

### ISSUE THREAD

**Issue by quantumSuperposition** [p455w0rd/DankNull#318]
Dank Null Version: 1.7.101
p455w0rds Lib Version: 2.3.161
Forge Version: 14.23.5.2847

Steps To Reproduce:
1. Stand in the air, either flying or at the edge of a block.
2. Shift-click to open dank null (or space-shift-click to open if flying)
3. The dank null cannot be opened until the player's hit box is completely over a block.

Was this tested on Single Player or Server (or Both)?
~~This was tested on a server in survival.~~
Tested in both single player and on a server.

Was this tested with just Dank Null installed, if not what is the minimal set of mods to cause the issue?
~~Playing Project Ozone 3, but haven't tested Dank Null by itself.~~
Have tested Dank Null by itself and it still causes the issue mentioned above.

**Comment by quantumSuperposition** [comment]
EDIT: Just tested Dank Null by itself with p455w0rds Lib in the same version as said above in single player; it behaves the same way.

**Comment by cjm721** [comment]
Intended feature. You can use the keybind to open when in midair.
