### ISSUE TITLE
Dank Null Stores all Items correctly but doesn't display the correct items.

### ISSUE THREAD

**Issue by twgecko** [p455w0rd/DankNull#319]
Dank Null Version: 1.7.91
p455w0rds Lib Version: 2.3.161
Forge Version: 14.23.5.2847

Steps To Reproduce: Seems to happen in all scenarios

Video of Bug: https://youtu.be/-rqepvJ7svc

Was this tested on Single Player or Server (or Both)? Server

Was this tested with just Dank Null installed, if not what is the minimal set of mods to cause the issue? Was tested using Omnifactory version 1.2.2

**Comment by cjm721** [comment]
You are on old version, if you replicate on latest create a new ticket.
