### ISSUE TITLE
Creative danknull

### ISSUE THREAD

**Issue by ghost** [p455w0rd/DankNull#320]
I can't figure out how to make items infinite with the creative dank null. I've checked the config options to see if it was a toggle-able feature but can't seem to find anything. I've also tried all the options listed in the dank null interface but no matter what, the items placed inside the creative dank null aren't infinite.

**Comment by cjm721** [comment]
For pulling out or placement? Its designed to be infinite for placement only, not with anything else.

**Comment by ghost** [comment]
Even in placement mode, in survival mode it seems to cost blocks to place?
