### ISSUE TITLE
Visual Sync issue with Emerald Dank Null

### ISSUE THREAD

**Issue by smilodon79** [p455w0rd/DankNull#322]
Versions:
DankNull-1.12.2-1.7.91.jar
p455w0rdslib-1.12.2-2.3.161.jar

Single Player or Multiplayer:  Only in Multiplayer

Steps to Reproduce:

1.  Create a fresh world
2.  Get an emerald dank null (not tested with other versions) and a drill [optional]
3.  Mine underground and keep adding items to the dank null
4.  Enable Ore Dictionary support for ores
5.  There's a visual sync issue in the dank null, making you not see accurate item or count in the slots
6.  I've wiped the player data and created a new world to test this issue.  It's consistently reproducible.  I have mekanism ores, thermal ores and tech reborn ores spawning in my world.

Refer attachment for more details.
![2020-07-18_18 21 14](https://user-images.githubusercontent.com/31346880/87862940-858efb80-c923-11ea-8408-c043ced49dfb.png)

Refer video attachment for steps to reproduce:
https://www.dropbox.com/s/ttotilhmc7i5kz1/Minecraft%201.12.2%202020-07-18%2018-18-22.mp4?dl=0

**Comment by smilodon79** [comment]
Update:

It's not just a visual sync bug.  After the steps listed above, remove all items except ONE item in the first slot.  Place it on the Docking Station and take it out.  Open the dank null and remove the item.  The item is still visually rendered inside the dank null.  Place in the docking station and take out again.  You can remove the item again.  You can repeat this as many times as you want, effectively duping whatever item you want in the game.

The duped item is not a visual glitch.  It actually exists and persists across re-login and can be used.

**Comment by cjm721** [comment]
Only latest Dank null is supported (which is currently 101)
