### ISSUE TITLE
My dank null turns granite and andesite into cobblestone

### ISSUE THREAD

**Issue by Mrnone9** [p455w0rd/DankNull#323]
Dank Null Version: 1.7.101
p455w0rds Lib Version: 2.3.161
Forge Version: 1.12.2

Steps To Reproduce:
1. Just place some granite down 
2. Mine it 
3. Some cobble will be added to dank null

Was this tested on Single Player or Server (or Both)?
Single Player
Was this tested with just Dank Null installed, if not what is the minimal set of mods to cause the issue?
FTB Revelations Pack

**Comment by Mrnone9** [comment]
I think i had a buggy null because i made a second one and it was working perfectly.

**Comment by jayschuster** [comment]
oredict was probably on for the first null, it automatically changes any picked up items that match the oredict, in this case probably "stone/tool/materials" into the item in the slot.
