### ISSUE TITLE
Items wont show on MK VI

### ISSUE THREAD

**Issue by NedeR1** [p455w0rd/DankNull#329]
Dank Null Version: DankNull-1.12.2-1.7.91.jar
p455w0rds Lib Version: p455w0rdslib-1.12.2-2.3.161.jar
Forge Version: 14.23.5.2854

Steps To Reproduce:
1. Put items on dank null
2. When i try to take out items, they dont show but i can eject them if i click the blank space
3.

Was this tested on Single Player or Server (or Both)? Yes, on single player items show, but on server doesnt show items

Was this tested with just Dank Null installed, if not what is the minimal set of mods to cause the issue?

**Comment by Codingale** [comment]
Same issue here, did you solve it or did it solve it's self?

I have cobble in the first slot, but it shows like iron ore, clicking the first slot gives me a stack of cobble properly... I'm super confused, because I used this before with no issues at all.
