### ISSUE TITLE
Feature request - configurable hotkeys

### ISSUE THREAD

**Issue by Nightcaste** [p455w0rd/DankNull#34]
Currently /dank/null does not have any entries in the minecraft controls options, so I can not reassign functions to different keys or mouse actions.  I use mouse4 for the push-to-talk on voice comms, and /dank/null uses this to cycle through the gadgets contents, I would like to be able to unlink that functionality.

**Comment by p455w0rd** [comment]
good argument..i'll add it :)

**Comment by p455w0rd** [comment]
![](http://p455w0rd.net/u/12.34.14-16.12.17.gif)
