### ISSUE TITLE
[1.12] unable to remove /dank/null from docking station

### ISSUE THREAD

**Issue by p455w0rd** [p455w0rd/DankNull#36]
For now, just remove the item in your offhand, this is technically a bug, and I'll treat it as such

**Comment by BigIrukandji** [comment]
How do you remove the dank null from the docking station from your offhand? That doesn't make sense to me. I currently have a dank null in the docking station that cannot be removed.....I've tried everything.

**Comment by p455w0rd** [comment]
remove the item in your offhand? (have empty hands)

**Comment by BigIrukandji** [comment]
I misunderstood you, that worked..thanks!

**Comment by p455w0rd** [comment]
![](http://p455w0rd.net/u/10.16.54-16.12.17.gif)
