### ISSUE TITLE
[1.12] stop spamming chat with selected block

### ISSUE THREAD

**Issue by fabbe50** [p455w0rd/DankNull#37]
Please use the toast system instead of spamming the chat when selecting blocks/items...

**Comment by p455w0rd** [comment]
that would be even worse..but I already have a fix for this :) ..i'll mark this as a feature request...chat spamming annoys me too..but so do the toasts..that system was just a horrible idea to start with

**Comment by fabbe50** [comment]
Great to hear that you have a fix for it, doesn't matter how you do it! As long as spam goes away! Thanks!

**Comment by p455w0rd** [comment]
![](http://p455w0rd.net/u/08.43.44-15.12.17.gif)

**Comment by fabbe50** [comment]
Great work!
