### ISSUE TITLE
Selecting of blocks while GUI is open [Feature Request]

### ISSUE THREAD

**Issue by hypernova132** [p455w0rd/DankNull#38]
I get annoyed by having to scroll to a block every time I want to use it. This is the same reason I never use the scroll wheel to move between items on my hotbar. I'd like to instead be able to click on a block or item while the GUI is open to select it. I'm sure I'm not the only one that gets annoyed by having to use the scroll wheel.

**Comment by p455w0rd** [comment]
hold alt+click the item you want selected
