### ISSUE TITLE
oredictionary [feature request]

### ISSUE THREAD

**Issue by Staegrin** [p455w0rd/DankNull#39]
Could it be made possible to add oredictionary to the dankNull? If you have ores for instance and want only one slot to be used. Different versions of copper -> get turned into one type

**Comment by p455w0rd** [comment]
maybe next release I can figure out something..problem is that there is a lot more than just ores using the Ore Dictionary...this might not be a problem at all or maybe be a major one..for now, I will release with current new features implemented/bugs fixed as per issue labels in this tracker...it is a good idea though..thanks for taking time to suggest it :)

**Comment by chimericdream** [comment]
Perhaps this could be a per-slot setting, similar to the extract mode? That way, it's up to the player to make the decision. The target variation of the oredicted item would be the one originally placed into the DankNull, and anything else matching the ore dictionary for it would be auto-converted.

**Comment by p455w0rd** [comment]
oo... @chimericdream this would be a lot more feasible

**Comment by p455w0rd** [comment]
https://twitter.com/TheRealp455w0rd/status/953661033511641088 :)

**Comment by ElvenChaos** [comment]
Does this open up potential dupes? If resources are automatically listed under broad ore dict entries, will it try to convert on that? And how does this fare with items with multiple oredict entries?

If this does open up problems, you could add a white/black list to the configs so pack makers can account for the above.

**Comment by p455w0rd** [comment]
well..i thought about this...but I remember I added Item whitelisting/blacklisting...however I forgot that was just for the creative version..so this is definitely still valid..so yeah..atm, it definitely will dupe..and say there's 2 oredict entries: `blockStone` and `blockSmoothStone`..if the item being picked up matches either of those, it'll get added as the item with oredict enabled in the first applicable /dank/null..so I definitely have some work to do here and I'll get on it now..thanks for pointing this out...so just so we're clear..a whitelist blacklist of oredict names would suffice? 
example:
`S:OreDictionaryBlacklist=oreIron;gemLapis`
same format would apply to whitelist and whitelist would take precedence

**Comment by ElvenChaos** [comment]
I think it should. In my head, I'm comparing this to what Pam's HarvestCraft does to food items, and what UniDict does to just about everything. They both like to add broad list-type ore dicts (listAllmeatcooked, blockMetal) that can be useful, but should never be treated as "equivalents" as oredict was originally intended for. I would add one more config option to "blacklist everything, use whitelist." In these cases, it may be easier to describe what items are "junk" as opposed to what isn't.

**Comment by p455w0rd** [comment]
I'm going to close this and create a new issue specifically for the black/whitelists
