### ISSUE TITLE
[1.12] Dedicated Server Error when placing a block

### ISSUE THREAD

**Issue by MacAttack-UK** [p455w0rd/DankNull#4]
When trying to place a block from the /dank/null tool when connected to a dedicated server it does not work and throws an error into the latest.log

This does not happen in single player.

All testing done on a freshly built dedicated server instance.

Minecraft : 1.12
Forge : forge-1.12-14.21.1.2443-universal

Mods : 
DankNull-1.12-1.0.2
p455w0rdslib-1.12-2.0.18
CodeChickenLib-1.12-3.1.2.297-universal
RedstoneFlux-1.12-2.0.1.2-universal

latest.log : https://pastebin.com/HtDN24xB
fml-server-latest.log : https://pastebin.com/Jf00ESuf

Also why does it require 2 x Libs and a mod just to run the /dank/null mod?

**Comment by ProsperCraft** [comment]
We are having the same issue on 1.12.1

https://gist.github.com/ProsperCraft/1e0fc77ff59746dac006823abd1debe9

Forge - forge-1.12.1-14.22.0.2474
DankNull-1.12-1.0.2.jar

**Comment by p455w0rd** [comment]
Thanks so much for the reports! I have finally found time to look into this and have fixed it in dev..I'll be pushing builds to CurseForge momentarily :)

**Comment by p455w0rd** [comment]
@MacAttack-UK You are far from the first to ask this, and therefore, I have written an article on the FTB subreddit to shed some light on why we use libs the way we do. Please reference https://www.reddit.com/r/feedthebeast/comments/725rva/psa_regarding_library_mods/

**Comment by MacAttack-UK** [comment]
Awesome thank you very much, I'll add it back into our Dev Pack for testing, I've missed it lots lol
