### ISSUE TITLE
JEI recipes broken in the last update

### ISSUE THREAD

**Issue by DrakusorU** [p455w0rd/DankNull#41]
In the latest update, the recipes are not showing in JEI, only descriptions/information about the item.. tried with 2 instances, one was my modpack and one was a new instance with very few mods to see if there was a conflict.. the items are still craftable if you remember the recipe to do it, its just that they are not showing in JEI

**Comment by Morpheus1101** [comment]
Can confirm this is indeed a thing

**Comment by p455w0rd** [comment]
yay lol..will get a hotfix out asap assuming i can figure out why lol

**Comment by p455w0rd** [comment]
wow..ok..so i had to move ModEvents.init() to preinit and add a method that return ModRecipes#getRecipes in array format...will be uploading soon, thanks!
