### ISSUE TITLE
[Request] Option to lock slot or leave 1 block when extracting.

### ISSUE THREAD

**Issue by chimericdream** [p455w0rd/DankNull#43]
I like being able to put the /dank/null on the docking station when I come back from mining to drop off all my collected things. But what I don't like is needing to re-configure which items I want the DN to pick up every time I go out to mine.

It'd be nice if there was an extraction option along the lines of "Extract from all slots, leave 1 item in each slot". Alternately, if the DN had an option to lock the slots based on the current contents, that would work as well.

**Comment by p455w0rd** [comment]
there is..get most recent version and hover over slots with items

**Comment by SgtSnipey** [comment]
Does this work with building aswell?

**Comment by chimericdream** [comment]
I'm still having issues with this. I have a Mk VI dank null, and I have selected "extract all but one". However, everything gets pulled out. Is this due to the method by which I am pulling items? I'm using itemducts and servos from Thermal Dynamics. I also tried this with "all but 16" and "all but 64". each case was the same.

A brief test with a hopper suggests that this may be due to servos extracting more than one item at a time. If the amount you currently have is an even multiple of the amount you want to leave in the DN, everything will get pulled out no matter what.

**Comment by chimericdream** [comment]
Completely understandable. I'm about to head to work myself.

**Comment by SgtSnipey** [comment]
Does it stop it from using it when ur building?

**Comment by p455w0rd** [comment]
no..this setting is just for the docking station

**Comment by SgtSnipey** [comment]
Can it be adding for building? Or some way to lock them in place?

**Comment by SgtSnipey** [comment]
The Issue I have is I have it sorted a certain way, and then I use the lastone and its gets messed up.

**Comment by p455w0rd** [comment]
i'm always open to a good arguement when someone wants a new feature..but I can't think of a good one for putting a limit on use...keep an eye on the number left and don't use them all..also position/sorting doesn't matter..extraction modes are kept per-/dank/null even if the item is fully emptied..upon putting another of that item in, the settings are maintained

**Comment by p455w0rd** [comment]
how does this sorting help? how does the sorting changing screw anything up? (other than OCD)

**Comment by p455w0rd** [comment]
i just thought of something...what I could do is display the number left of the currently selected item somewhere on the HUD...if you would like for me to do this, create a new issue requesting it and I'll implement it :)

**Comment by SgtSnipey** [comment]
When you use it build it helps to know what order the mats are in so you don't have to think about switching between them

**Comment by p455w0rd** [comment]
see the gif in #50 ...if you wanna preserve the sorting, simply don't use the last of that item when building (after next update)...I am not 100% ruling your idea out as I can see other player having the same opinion, it just can't happen right now due to time constraints

**Comment by p455w0rd** [comment]
back to what this issue is about (just so i don't get lost when reviewing before pushing next update)...the bug is when items are extracted from docking station using a method that extracts more than one item

**Comment by SgtSnipey** [comment]
Just Wanted to say Thank You :D And Keep up the great love your mod :D

**Comment by p455w0rd** [comment]
short gif..note the extraction modes:
![](http://p455w0rd.net/u/10.47.34-24.12.17.gif)
this is the same thing affecting the themal itemducts

**Comment by p455w0rd** [comment]
I changed this to show only the items available for extraction...so mods trying to view the inventory of the docking station will only see the amount of items available now
http://p455w0rd.net/u/10.40.42-28.12.17.gif
