### ISSUE TITLE
Accessing from Refined Storage system

### ISSUE THREAD

**Issue by hypernova132** [p455w0rd/DankNull#45]
I'm using refined storage amount a lot of other mods, including this one. When I attach an external storage to the docking station and have the /dank/null on the docking station, I can view the items in it's inventory from the grid. However, I can't access the items from the grid. I'm not sure if this is a bug as I've not tested it with applied energistics or any other mod with storage networks that can connect to outside inventories besides refined storage. I'd like to be able to access the items from the refined storage grid so I can pull items from it to craft using the refined storage system while it's on the docking station.

**Comment by p455w0rd** [comment]
Make sure the extraction mode for the item you wish to extract is not set to `Do not extract`...if it still doesn't work, it's on raoul's end...works perfectly in AE2

**Comment by p455w0rd** [comment]
however, in the current public version, when accessing the inventory from a storage bus or even a pipe system that extracts more than 1 item at a time (Thermal Dynamics itemducts for instance), you can pull more than the set extraction mode..this is mentioned in #43 and has been fixed in dev
