### ISSUE TITLE
[1.12.2] Unlimited blocks

### ISSUE THREAD

**Issue by TheBolly** [p455w0rd/DankNull#46]
Hey!

I run a server and a player bought to my attention that when using the Dank Null they can place unlimited numbers of the block they put in it. Is it possible to limit the amount as it should or is this a problem with the mod itself.

I'd tried this myself and the same thing happened for me.

If this could be looked into that would be great.

Thanks,

Bolly

**Comment by Morpheus1101** [comment]
i've tested this using all variations of the /dank/null and i cant re-produce this issue.  Could u supply the Forge version and dank/null version your currently using

**Comment by GammaCaster** [comment]
Not sure which direct version but the latest FTB Horizons modpack does this. I've used it as a dupe on SMP servers.

Basically when placing a block with the dank null whatever you have selected never runs out. I can make 1 diamond block, put it in the DN, and then use the DN to place as many diamond blocks as I want. Ive even packed a Strongbox from Thermal Expansion into this thing and used the DN to dupe it.

**Comment by Morpheus1101** [comment]
I've loaded the FTB Horizons III pack and tested in SP & SMP and i cant re-produce this issue .. have u manually added in any other mods ?

**Comment by GammaCaster** [comment]
Just tested in Single Player FTB Horizons 1.4.0

The Jar filename is DankNull-1.12-1.0.14.jar

Created single player world in creative mode with default settings

Spawned myself in a tier 1 Dank Null

I put a block into the first slot and placed it. It was not infinite and worked as expected. Tried it with two other blocks and same result.

Then I put three different blocks into the Dank Null in Slots 1, 2, and 3. I left shift+mouswheel to select Slot 3. I was able to place infinite items. In fact when I left shift+mouswheel back to Slot 1 I was able to then place infinite items from Slot 1 as well.

**Comment by GammaCaster** [comment]
Tested DankNull version 1.2.19 in Single Player by swapping the jar file out from the FTB Horizons 1.4.0 modpack for the updated version.

The bug was not present in version 1.2.19. All items were dispensed as expected and no duplication occurred.
