### ISSUE TITLE
Recommendation

### ISSUE THREAD

**Issue by mohler7154** [p455w0rd/DankNull#47]
Not sure if this is the right place to post this, but I have an idea, that if it worked would be a good change.  I am using the DankNull while also using chisel and bits.  After the bit bag fills up I used the DankNull to get rid of the excess bits I created that were all over the place.  It would be great if chisel and bits could be used in conjuction with the DankNull pulling them out, much like the builders wand is able to pull blocks out of the dank null while building.  This would make the bit bag unnecessary and make the dank null like a much improved version of the bit bag that also voids excess bits.

**Comment by p455w0rd** [comment]
The reason the /dank/null works with BBW is because portablejim added support for pulling items out of items that implement Forge's IItemHandler capability. This would be on AlgorythmX2 to add such support.

**Comment by mohler7154** [comment]
Gotcha.
