### ISSUE TITLE
[1.12.2] NEI & Control Click

### ISSUE THREAD

**Issue by mac2040** [p455w0rd/DankNull#48]
It not an error but if you have Not Enough Items 1.8.+ install the control click functions to change extract mode does not work thanks

**Comment by p455w0rd** [comment]
sent a DM on discord to `mac2040#1781` if this is you, pls check discord DMs

**Comment by p455w0rd** [comment]
@covers1624 after looking at NEI src, it appears that this shouldn't be conflicting as IInputHandler#mouseClicked should be returning false in the NEIClientEventHandler event methods..but it is in fact conflicting...can you please halp...what do I need to do to be able to have my ctrl+click work? I've abstracted the click stuff from the GuiScreen#handleMouseInput to an event (specifically `net.minecraftforge.client.event.GuiScreenEvent.MouseInputEvent`)..I just dunno how I can get priority with you setting EventPriority.HIGHEST

**Comment by covers1624** [comment]
Ah, poke me on ts or discord so I remember to check this out tomorrow morning, already in bed and can't be fucked getting up..

**Comment by p455w0rd** [comment]
@covers1624

**Comment by p455w0rd** [comment]
@mac2040 mind joining my discord so I can throw you a copy with the fix to confirm it works for ya? https://discord.gg/9J7yhUP
