### ISSUE TITLE
[1.12.2] Make /dank/null renamable

### ISSUE THREAD

**Issue by Daihok41** [p455w0rd/DankNull#49]
This is just a suggestion but maybe add a way for us to name our dank/nulls? For in stance i carry like 3 on me right now. 1 is for building block types, another for any kind of seeds and flowers and then another for trees and saplings and such. Would be awesome if we had some way to tell them apart when in inventory.

**Comment by p455w0rd** [comment]
so I just tested...they're already nameable via the vanilla method (an anvil) lol
