### ISSUE TITLE
[Request] Display quantity of current item in hotbar/inventory

### ISSUE THREAD

**Issue by chimericdream** [p455w0rd/DankNull#50]
> (quoted from #43)
> i just thought of something...what I could do is display the number left of the currently selected item somewhere on the HUD...if you would like for me to do this, create a new issue requesting it and I'll implement it :)

I don't know why it didn't occur to me, but I had no idea how much I wanted this feature until you mentioned it. 😁

**Comment by p455w0rd** [comment]
What do you think?
![](http://p455w0rd.net/u/12.34.46-22.12.17.gif)

**Comment by chimericdream** [comment]
WOW. I was literally just thinking it'd be the small text in the hotbar itself. That's much nicer. Only question I'd have is whether that display persists as long as you're holding the /dev/null or if it appears briefly when switching items. My preference would be for it to persist (or be configurable).

**Comment by p455w0rd** [comment]
it persists and only shows if the /dank/null has items in it :)

**Comment by p455w0rd** [comment]
also truncates selected item name accordinlgy: http://p455w0rd.net/u/12.54.43-22.12.17.mp4

**Comment by chimericdream** [comment]
:shipit:

**Comment by p455w0rd** [comment]
i will when covers gets back with me on the NEI issue lol

**Comment by chimericdream** [comment]
Sweet. I just noticed in the screencaps that you didn't have any items with > 64 items. I don't see why that would make a difference, but just in case, does it?

**Comment by p455w0rd** [comment]
rewatch lol there's 121 stone slabs..the first item in the gif

**Comment by chimericdream** [comment]
[![I feel sheepish](https://i.imgflip.com/3eopb.jpg)](https://i.imgflip.com/3eopb.jpg)
