### ISSUE TITLE
Requires 2 placements to place a block

### ISSUE THREAD

**Issue by Mawty** [p455w0rd/DankNull#52]
Since Mk2 i've encountered a bug where if I place a block it is invisible but has bad collision. You have to place it again at the same spot in order for it to place properly. Now at the mk5 that's all you are able to do, I cannot place anything properly. I've also seen others have the same issue on streams.

**Comment by p455w0rd** [comment]
yup..likely due to FTBUtils chunk claiming stuff..should be fixed by #44

**Comment by DrakusorU** [comment]
mind if I ask when you are gonna push this update ? :D

**Comment by p455w0rd** [comment]
waiting on covers to help with the NEI issue

**Comment by TwiZtedXero** [comment]
This is also causing it to leave the placed block in the null, aka duping the block.

**Comment by p455w0rd** [comment]
I'm not home right now, but I can whip up a pre release to ensure this is fixed if u join my discord....when I get home that
