### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by chimericdream** [p455w0rd/DankNull#54]
The latest version causes a server crash during startup. It's getting a `NoClassDefFoundError` exception looking for `net.minecraft.client.entity.EntityPlayerSP`. [Here is the full crash log.](https://gist.github.com/chimericdream/256b910e6587c6aeb67734f6f7cdcae6)

**Comment by p455w0rd** [comment]
shit..thanks lol..will have new version up momentarily

**Comment by jeckhart** [comment]
Just curious, what causes this type of error? Is it build related?

**Comment by Morpheus1101** [comment]
Looking id say its a SinglePlayer class trying to load in a multiplayer instance

**Comment by p455w0rd** [comment]
oh yeah..it was a reference to `Minecraft.class` in `DankNullUtils.class`..The `Minecraft` class is no accessible server-side. I had forgotten to annotate the method to be client-only.

**Comment by wgaylord** [comment]
Annoyingly FTB shipped their Release of FTB Horizons III with this broken version.
