### ISSUE TITLE
Placing blocks from /dank/null doesn't trigger update on adjacent blocks

### ISSUE THREAD

**Issue by chimericdream** [p455w0rd/DankNull#55]
I was clearing out some water with dirt from the DN, and I noticed that the flowing water didn't update until I either placed another block from my inventory or broke a block under where the water was.

Edit: This is with 1.12-1.3.24

**Comment by p455w0rd** [comment]
you should join my discord as much as we communicate lol https://discord.gg/9J7yhUP seeing if i can reproduce this now

**Comment by p455w0rd** [comment]
successfully reproduced..working on it :)

**Comment by p455w0rd** [comment]
I do believe I have fixed it..would love for you to drop by discord so I can send you a version to test
