### ISSUE TITLE
Blocks not placing

### ISSUE THREAD

**Issue by SgtSnipey** [p455w0rd/DankNull#57]
The update fixed the FTB unitys issues client side only, Members on my server can't see blocks if placed by the Dank Null ATM.

**Comment by p455w0rd** [comment]
hmm..the player is placing them..very odd

**Comment by p455w0rd** [comment]
got ftb utils loaded..blocks are placing fine in SMP in claimed and unclaimed chunks...mind giving me a modlist/pack name? are you running sponge/plugins?

**Comment by p455w0rd** [comment]
are they using optifine? if so, have them try the latest preview (C8)

**Comment by SgtSnipey** [comment]
No one is using optifine, Ill work on the mod list. we are running direwolf20's new pack plus. Ill get as list of added mods.

**Comment by SgtSnipey** [comment]
Mod List Added: : ET Lunar, G.L.A.S.S., Immersive Petrol, Immersive Tech. Malissis Doors, Angel ring to Bauble, BiblioCraft, FarmingforBlockheads, Open Mod Turrets, Reliquary, Signals, Steve's Carts, Super sound Muffler, Viescraft, Water Strainer Cyclic.

**Comment by alpal01** [comment]
I don't recommend angel ring to bauble bc in the future the extrautils 2 new update breaks it

**Comment by SgtSnipey** [comment]
What update?

**Comment by alpal01** [comment]
extrautils 2 version: 1.7.2 if you update in the future i hope they update soon

**Comment by p455w0rd** [comment]
any news on this with 1.3.27?

**Comment by alpal01** [comment]
I have no idea bc I don't play on a server, sorry to ask you this but what is the latest un-broken version of this mod (sorry) for my modpack? In 1.3.24, the bug is not occurring for me but no sound when placing blocks and eventually crashed me

**Comment by p455w0rd** [comment]
1.3.27?

**Comment by alpal01** [comment]
ok I'll test with like 80 ish mods

**Comment by p455w0rd** [comment]
I'm hoping anyway lol..1.3.28 is pending approval..just one fix and it's the creative /dank/null being displayed on the wrong creative tabs

**Comment by alpal01** [comment]
so it looks like my only concern is: there is no sound when dank null places anything (my sound is working when I place stone manually)

**Comment by alpal01** [comment]
is that intended?

**Comment by p455w0rd** [comment]
can u make a new issue? that'll remind me..no..and I know why

**Comment by alpal01** [comment]
ok

**Comment by alpal01** [comment]
so I guess this issue is resolved hopefully, @SgtSnipey put the newest update on your server and have your server members test it out on the server, please...

**Comment by p455w0rd** [comment]
yeah I would rly like input from @SgtSnipey before I close the issue..thanks for all your help @alpal01 :)

**Comment by alpal01** [comment]
no probs :)

**Comment by alpal01** [comment]
yea out of all the new mods, this is basically my favorite thanks for making it

**Comment by SgtSnipey** [comment]
Sorry sir i will update the server and test it out.

**Comment by SgtSnipey** [comment]
Ok Still doesn't work in Claimed and Unclaimed chunks.

**Comment by p455w0rd** [comment]
yeah..it's something else in the pack then..it works fine now with fbtuils..would be awesome to find out what it is

**Comment by SgtSnipey** [comment]
Idk i could send you the code for our pack in twitch launcher and a world files might help ya?

**Comment by p455w0rd** [comment]
yeah..ship me a zip in discord DM..i'm done coding for the night, but I'll check it as soon as I can tomorrow..would rly like to get this resolved

**Comment by SgtSnipey** [comment]
I'll get it done tomorrow
