### ISSUE TITLE
Throwable Objects

### ISSUE THREAD

**Issue by mattwandcow** [p455w0rd/DankNull#58]
Loaded my Dank/null with bottles of enchanting and when I went to use it, the bottle was thrown and my dank/null disapeared in a smash of glass.

Loading up a new world did not replicate results, although if I try it in my established Project Ozone Lite world, it does, in fact, repeat.

Mod list shows the version as 1.10.2-2.2.32

**Comment by p455w0rd** [comment]
/dank/null (the mod) does not exist in 1.10.2..it only exists in p455w0rdsThings in 1.10.2, please post on the appropriate tracker
