### ISSUE TITLE
dupe bug

### ISSUE THREAD

**Issue by billynap** [p455w0rd/DankNull#59]
We are running a direwolf20 server and when you place a block with the dank/null it does not use up any of the blocks inside. for example: I placed a block of diamond inside and was able to place 9 blocks and still had the block inside the dank/null. this is true on all tiers of the block and also after testing is the same on our Rev Modpack server as will. please try to fix as we do not like to ban items from our servers. The players in our community use this block and are in love with it. Nice Mod! keep up the good work!

**Comment by p455w0rd** [comment]
try this on a local server with only CodeChickenLib, DankNull, and p455w0rdsLib..tell, me if you still experience

**Comment by billynap** [comment]
We are now thinking it has something to do with Sponge, or one of the plug-ins. working on eliminating them now. will let you know when I figure it out.

**Comment by p455w0rd** [comment]
ALSO...i'll be doing and update yet today...this should already be fixed in the prior version (which is still buggy) and all current bugs should be fixed in the next version

**Comment by p455w0rd** [comment]
any news on this with 1.3.27 ?

**Comment by billynap** [comment]
Works on a local server. My Server Dev left me the following message about the topic:

Maybe ask him to confirm which commit the fix is under so that we can look at the code changes and possibly port them over to our existing code if needed
