### ISSUE TITLE
DankNull-1.12-1.0.5 requires unavailable version of CodeChickenLib

### ISSUE THREAD

**Issue by CplPibald** [p455w0rd/DankNull#6]
Trying to launch with DankNull 1.0.5, it errors out saying it requires codechickenlib 3.1.3 or above.  However as of this writing, the latest version of CodeChickenLib available on curseforge is 3.1.2.297

https://minecraft.curseforge.com/projects/codechicken-lib-1-8

The CCLib page does have a link to unstable builds with the correct version number, but I'm extremely hesitant to add that to my server because A) it's probably listed as "unstable" for a reason, and B) Inflicting adf.ly downloads on all of my users is borderline cruel and unusual punishment.

Possible solutions in decreasing priority:
1. Convince CodeChickenLib authors to publish 3.1.3 to curseforge
2. Make DankNull work with CCL 3.1.2
3. If nothing else, please make a note of this dependency on the download page.

**Comment by p455w0rd** [comment]
this is 100% on @covers1624 's end..i have notified him...he's busy with factorio tho :P

**Comment by p455w0rd** [comment]
I'm going to reopen this..I created a PR...hopefully this gets taken care of soon
PR at https://github.com/TheCBProject/CodeChickenLib/pull/106

**Comment by CplPibald** [comment]
It looks like CCL uploaded version 3.1.3.

https://minecraft.curseforge.com/projects/codechicken-lib-1-8/files/2485334

**Comment by p455w0rd** [comment]
yeah, but it's not marked correctly on curse or in the mod itself

**Comment by covers1624** [comment]
My files are automatically uploaded by jenkins, completely forgot about changing the supported versions.
