### ISSUE TITLE
[1.12.2] Creative /dank/null everywhere *but* /dank/null creative tab

### ISSUE THREAD

**Issue by Boundarybreaker** [p455w0rd/DankNull#62]
For some reason, the /dank/null creative is in every tab except the /dank/null tab. It's even in the survival inventory tab, taking the place of the delete slot. Any idea what could be causing this/how to fix it?

/dank/null version 1.3.27, Forge version 1.12.2-14.23.1.2582

![2018-01-01_01 12 15](https://user-images.githubusercontent.com/6722691/34466675-32324150-ee91-11e7-9872-92c5196a641b.png)
![2018-01-01_01 11 58](https://user-images.githubusercontent.com/6722691/34466676-32684c3c-ee91-11e7-9954-ae20f4f0e3bb.png)
![2018-01-01_01 11 54](https://user-images.githubusercontent.com/6722691/34466677-328889fc-ee91-11e7-977d-27cc0f140b42.png)
![2018-01-01_01 11 41](https://user-images.githubusercontent.com/6722691/34466678-32a60806-ee91-11e7-9b8c-8d90d1f53a20.png)
![2018-01-01_01 11 34](https://user-images.githubusercontent.com/6722691/34466679-32bf8574-ee91-11e7-992a-f608959726e1.png)

**Comment by p455w0rd** [comment]
yeah..derp..minor bug..fixed in dev..thanks for reporting :)
