### ISSUE TITLE
Can't open /dank/null/ hud with right mouseclick

### ISSUE THREAD

**Issue by twoworlds** [p455w0rd/DankNull#65]
I updated /dank/null/ to version 1.3.29 
Minecraft 1.12.2

I cannot open the /dank/null/ menu when I click right with the /dank/null in my hand to make configurations. If I go mine, the /dank/null/ works and i can pull the items out of it using the docking station.

(Modpack is FTB Revelation)

**Comment by twoworlds** [comment]
Just discovered, that I can access the menu when i right click on the /dank/null/ standing on the docking station, bur not holding it in my hand

**Comment by p455w0rd** [comment]
try crouching?

**Comment by p455w0rd** [comment]
check #56

**Comment by PliskintheSaltyFork** [comment]
I have this same problem on a newer version (1.4.33) and crouching doesn't work.
