### ISSUE TITLE
random disconect on login 1.12 

### ISSUE THREAD

**Issue by unstablecraft** [p455w0rd/DankNull#66]
since a few days my server spits out this error as soon some logs
https://pastebin.com/S4cucvqT

dank null vers:  DankNull-1.12-1.0.14.jar

forge vers: forge-1.12.2-14.23.1.2566-universal.jar

sponge version: spongeforge-1.12.2-2555-7.0.0-BETA-2783

**Comment by p455w0rd** [comment]
update /dank/null ..the class crashing doesn't exist anymore

**Comment by unstablecraft** [comment]
okido ill ask ftb to hurry with the direwolf update 

thank you

**Comment by unstablecraft** [comment]
btw you are aware that 
 dank null's dupe  ??

**Comment by p455w0rd** [comment]
no need to bug snowshock...he's well aware of what I am doing..we stay in contact..and I've heard of /dank/null duping with sponge...I will not debug stuff with sponge..Forge is annoying enough...if you remove sponge and it still happens..then send me appropriate info and I'll look into it...sponge was not meant to work with forge and us mod devs get nothing good from it...for me..in an environment with /dank/null (latest), JEI, TOP, WAILA, and FTBUtils I do not experience this

**Comment by unstablecraft** [comment]
will do sorry for bothering

**Comment by p455w0rd** [comment]
nothing wrong with trying to help..I'm not being a dick..just being direct and informative..sorry if it comes off that way..I def appreciate you taking the time to try and help :)
