### ISSUE TITLE
[Suggestion] Config to change how dank/null should be opened

### ISSUE THREAD

**Issue by SHIuSH** [p455w0rd/DankNull#67]
My main problem is I can't shift-place blocks with dank/null. It always opens the GUI.
It would be very useful if you could specify things like

- what block are we looking at: interactable/notinter./both/neither 
- holding/notholding shift/ctrl etc.
- right click or left click

**Comment by Morpheus1101** [comment]
Yes that would be a god send, nothing more annoying then hovering close to lava an trying to sneak click a block an the gui opens :D

**Comment by p455w0rd** [comment]
added keybind option
