### ISSUE TITLE
suggestion: allow items to be piped into the block as well

### ISSUE THREAD

**Issue by LordHellscream** [p455w0rd/DankNull#68]
This mod is awesome, it would be even more awesome if base can allow items to be inserted through item pipe or hopper in in addition to extracting them.

**Comment by chimericdream** [comment]
I have mixed feelings about this idea. It basically turns the DankNull into a single-block equivalent of 54 Quantum Storage Units/Black Hole Units, which the OP gamer in me _LOVES_. But I also kind of feel like that isn't in line with the spirit of what the item is intended for.

I think I'm generally in favor of something like this, but I might like to see it implemented as a second type of docking station for the DankNull. Maybe have a full-block version of the dock which has a slot to hold a DankNull and allows items to be pumped in/out. The current dock could then be extract-only, if that's all you need/want, and the other version could be a second tier dock to allow extract/insert.

**Comment by p455w0rd** [comment]
Nope. Due to what chimeric pointed out. In modding, even through the drama, we are all part of the same community. If I were to do such a thing, this would invalidate quite a few other mods. Some of which are created/maintained by good friends of mine. This is out of the question.
