### ISSUE TITLE
Crash on filling all slots in /dank/null MK V (emerald)

### ISSUE THREAD

**Issue by Zedrimar** [p455w0rd/DankNull#7]
Here is the section of the log with the crash report. not sure what caused it :/ https://paste.ubuntu.com/25642356/

**Comment by p455w0rd** [comment]
Thanks for the report. This happens sometimes when slots are clicked too fast. I'll get a fix out asap. This is an error on my part.

**Comment by Zedrimar** [comment]
ok, thanks! ^-^ great mod btw! I absolutely love it! :D

**Comment by Zedrimar** [comment]
Hooray its fixed! :D
