### ISSUE TITLE
Opening Issues.

### ISSUE THREAD

**Issue by SgtSnipey** [p455w0rd/DankNull#71]
Cant open in in mid air or on half slabs. On latest versions.

**Comment by p455w0rd** [comment]
didnt know about half slabs..mid air is intententional..if you're building a bridge by crouching+walking backward and placing blocks, this would normally cause the GUI to open and the player would fall (likely to their death)..i'll look into the slabs

**Comment by SgtSnipey** [comment]
Ok good point didnt think about that

**Comment by p455w0rd** [comment]
fixed the slab issue in dev
