### ISSUE TITLE
[MC 1.12, 1.3.29] Item duplication on Ctrl-Click

### ISSUE THREAD

**Issue by Tetha** [p455w0rd/DankNull#74]
Hey,

I am using a changed FTB relevation, running /dank/null 1.12-1.3.29 on Minecraft 1.12. Feel free to ask if you need more versions, but this seems isolated to the /dank/null UI. 

I can duplicate items in the following way:

 - Place an Item in the /dank/null. I tested this with 5 seeds, 8 arrows, 4 zombie chunks from mystical agriculture. Seems independent from the item stack.
 - Ctrl-Click the Item, so the slot is set to any of "Extract all but 1", "Extract all but 16" or "Extract all but 64". 
 - Take out the item manually by clicking on the stack
 - Now, Ctrl-Click the empty slot you just took the item out of. This leaves me with an itemstack in hand and an itemstack in the /dank/null. These have the same item and the same itemcount as the itemstack in the slot originally. There is no accompanying log message. 
 - You can repeatedly take the item out and ctrl-click the slot to get another two itemstacks, one in hand and one in the /dank/null. 
 - Ctrl-Clicking the slot while there is a cheaty stack in there works normally and just cycles the extraction mode. 

If I close the /dank/null UI and Ctrl-Click on a previously cheaty slot, there are no duplicated items. It looks like the UI is caching or not clearing the item stack, and the handler for the Ctrl-Click duplicates it. 

Edit1: The items persist unloading + reloading my single player world, so this is not visual. And I'm not in creative, just double-checked that.

Now excuse me while I cry and drop several dozen stacks of emerald blocks into lava.

**Comment by p455w0rd** [comment]
lol..thanks for the report..i'll look into it :)

**Comment by p455w0rd** [comment]
well..sucks I didn't catch this before the update yesterday...i have reproduced tho..thx for the report :)
