### ISSUE TITLE
Insert into /dank/null

### ISSUE THREAD

**Issue by Alex-hawks** [p455w0rd/DankNull#75]
Could it be possible to insert or extract but not both from the /dank/null on a per slot basis? This would be to turn the /dank/null into a viable builder's tool instead of just a miner's tool

**Comment by p455w0rd** [comment]
if you mean insert via the docking station, then no...this would invalidate mods like YABBA/StorageDrawers/Quantum Storage..the point of this mod purely to help when manual mining...

**Comment by Alex-hawks** [comment]
I was more meaning so we can resupply torches, for example. I'm not asking to be able to do both on a slot at once, the player would have to chose between automated insertion or automated extraction on a per slot basis
