### ISSUE TITLE
(DW20)Items on cursor when closing Dank/Null UI = Desync with added Server Crash on disconnect

### ISSUE THREAD

**Issue by ConnorMiner** [p455w0rd/DankNull#76]
When taking out items from a Dank/Null, upon closing the UI with items on the cursor, inventory interaction with blocks in the world becomes impossible. When an affected player is disconnected through any means, the server will then crash due to a double-disconnect error.

Expected Behavior:
Items are dropped or put in the player inventory.
Actual Behavior:
The player is unable to interact with the world, and a server crash is unavoidable without (possibly) stopping/restarting the server.

**Comment by p455w0rd** [comment]
wut?

**Comment by ConnorMiner** [comment]
I realized that it was Botania having problems with an update to Baubles, not Dank/Null having issues, so I closed this issue so that it wouldn't appear as an open issue for this mod.
