### ISSUE TITLE
JEI and NEI

### ISSUE THREAD

**Issue by Zedrimar** [p455w0rd/DankNull#8]
Love your mod but could you make it so that the recipes show in both NEI AND JEI by chance? I hate it when I have to switch between modes because items become hidden in one or another.... Sadly a lot of modders forget about NEI

**Comment by p455w0rd** [comment]
NEI in 1.10+ is a JEI addon...afaik, NEI just adds the widgets..not it's 1.7.10 and prior Recipes API... @covers1624 can you confirm? at any rate, no..JEI is now the standard...I have all but forgotten about NEI...covers is a good friend and current maintainer of NEI...I spent many nights trying to convince him to bring NEI back in its full flavor (as a standalone mod), but he has decided against, this and now I believe it was for the better...

**Comment by Zedrimar** [comment]
I mean, I get it. I just find that some mods favor NEI over JEI while others go for JEI over NEI and its annoying -_- I am sorry, I was just wondering. If you don't go and add support for NEI, I don't blame you. it's just nice to be able to use both viewing modes without having hidden items specific to one or the other

**Comment by p455w0rd** [comment]
i'm seriously lost as to what you are talking about...i'll await covers' response

**Comment by covers1624** [comment]
NEI is really almost just NotEnoughWidgets at this point, it has an alternate item panel, all the widgets, and dumps, it integrates with JEI and shows recipes through that aswell as hiding things that jei does. NEI does not handle recipes in any way shape or form, its Recipe api is archived and is no longer used. Really not sure what you are doing but i assure you NEI does not do any recipes it asks jei to display the recipe.

**Comment by p455w0rd** [comment]
thank you

**Comment by Zedrimar** [comment]
ah alright
