### ISSUE TITLE
Sugestion- Exchanger Compat

### ISSUE THREAD

**Issue by CTH999** [p455w0rd/DankNull#80]
So, It's able to work with [Better Builders Wands](https://minecraft.curseforge.com/projects/better-builders-wands?gameCategorySlug=mc-mods&projectID=238403)

It would be nice it it could work with The [Exchangers](https://minecraft.curseforge.com/projects/exchangers) Mod In much the same way. It would be able to pull out of and put into the DankNull.

I just think this would be beyond helpful!

Thanks!

**Comment by JackyyTV** [comment]
Hey there, I am the dev for Exchangers. I am actually currently working on that on my side. However, I am having some issues with implementing the compat but hopefully that will be resolved soon and the new version should be out in the coming few days!

**Comment by p455w0rd** [comment]
I will help when I get a chance..caps do take some getting used to, but I fully understand them now...They're simpler than they appear at first for sure..just takes practice :)

**Comment by CTH999** [comment]
Ok, I didn't see that one coming, so thanks!

**Comment by p455w0rd** [comment]
I am going to close this since it's on Jacky's side..if this hasn't been requested on that repo, you're welcome to make an issue there.

**Comment by CTH999** [comment]
Ok!

**Comment by CTH999** [comment]
It's been added In [Here!](https://github.com/JackyyTV/Exchangers/issues/46)

**Comment by p455w0rd** [comment]
i know..i tweeted bout it the day Jackyy released :P
