### ISSUE TITLE
GUI support for Chiseled blocks

### ISSUE THREAD

**Issue by richraid21** [p455w0rd/DankNull#81]
**Current Behavior:** 
The tooltip when holding the block shows you the selected item. However if the item is a chiseled version of a block, the type is not indicated. 

**Desired**
If the block is a chiseled version, show the chisel name also. This will help differentiate when a player has multiple different chiseled types.

**Comment by p455w0rd** [comment]
So I took your word for it that this was true...added CTM & Chisel to my dev env..created an Integration class in preparation for adding this functionality..and then decided to test before I moved forward...looks fine to me..
![](http://p455w0rd.net/u/13.09.44-06.02.18.png)

**Comment by p455w0rd** [comment]
Since I went through all that, I figured I'd adjust where the variant name is displayed...
![](http://p455w0rd.net/u/13.52.38-06.02.18.png)
