### ISSUE TITLE
How many can the dank\null hold?

### ISSUE THREAD

**Issue by ghost** [p455w0rd/DankNull#83]
I know I'm asking for a facepalm, but is there some way to see the max that a given tier can hold?

**Comment by p455w0rd** [comment]
![](http://p455w0rd.net/u/20.07.38-18.02.18.gif)
I'll mark this as a feature request because too many people ask..I'll just add it to the item tooltip

**Comment by ghost** [comment]
Yeah, facepalm alright. Thanks.

**Comment by Araxidis** [comment]
I love this mod ... makes mining much more bearable. I also love that you have added the tool tip. I currently have a Mk V with 2669 cobble in it so I am guessing the tool tip is not correct. This is what I got in creative mode:
/dank/null = 9 * 2 stacks (64)
/dank/null/MK II = 18 * 8 stacks (512)
/dank/null/MK III = 27 * 18 stacks (1152)
/dank/null/MK IV = 36 * 32 stacks (2048)
/dank/null/MK V = 45 * 50 stacks (3200)
/dank/null/MK VI = 54 * at least 1280 stacks (19K) (I stopped counting)

**Comment by Chinthor** [comment]
I concur with Araxidis. My MK IV holds double what the tip says it should.

**Comment by p455w0rd** [comment]
![](https://puu.sh/Cv5Zb/cda7aff671.gif)

**Comment by Markus-SJ** [comment]
Thank you
