### ISSUE TITLE
Crash when opening someone else null.

### ISSUE THREAD

**Issue by MrSapient** [p455w0rd/DankNull#84]
I get kicked from the server and it says "Network Disconnect: A fatal error has occurred, this connection is terminated" and then gives me this error in my console. https://pastebin.com/CHLmG5RR 

This happens every time i click on a docked diamond dank null that was made by another person on the server. it does not happen when i click on my emerald null. 

Forge 14.23.2.26.18 
DankNul 1.12-1.4.33

Was not using any of the following..  Optifine - BetterFPS - foamfix ..
it is a normal forge server.
Does not happen in single player world. ( i think its because i made the null and placed it not another person )

**Comment by p455w0rd** [comment]
thank you for providing good context :) I will fix this with a null check on my end, but it really should not be possible as I set an NBT tag with the value that is returning null on the receiving end..could be Forge, MC, or another mod messing with packets..but somewhere packets are being corrupted..I'll look into this after I get home from work..thank you for reporting

**Comment by p455w0rd** [comment]
so while investigating this, I've discovered that the issue is pretty deep..it's to do with packet handling..it's a long and tedious process as after most changes i have to relaunch 1 server instance and 2 client instances to test changes..I'll get there, but this could definitely take some time
