### ISSUE TITLE
Scoria Stone

### ISSUE THREAD

**Issue by Rixxaw** [p455w0rd/DankNull#85]
Scoria stone from PrimalCore spawns in the nether.  Dark Red Stone block... For some reason when it goes into the dank null it seems fine, but when you go to place it, it changes to "Stacked Scoria Stone" and it places like 1 block away from where you tell it to place, leaves like a GAP.  As a work around I just don't put it into the Dank Null anymore.

**Comment by p455w0rd** [comment]
likely due to odd NBT handling..same happens with any IC2 TileEntity..i'm going to try to come up with a fix, thanks for reporting

**Comment by p455w0rd** [comment]
Also, this mod is closed-source and All Rights Reserved, so I can't legally decompile/deobfuscate it to find out what exactly is going on to guarantee this is the problem...I can only hope that by fixing IC2 tile entities, that this will be fixed as well
