### ISSUE TITLE
Support 'pick block' button for fast selection

### ISSUE THREAD

**Issue by Daenyth** [p455w0rd/DankNull#86]
I'd like the pick block button to select the targeted block type for placement if the /dank/null contains the targeted block. This would make base building a lot more convenient, because you wouldn't have to shift scroll, just single button press to switch building blocks.

**Comment by p455w0rd** [comment]
you can also open the GUI and Alt+click the block...but I do like this idea..I'll see what I can do..thanks for the suggestion

**Comment by Daenyth** [comment]
Yes, I'm aware of the gui. I'm not sure that key combo works on Mac though.

**Comment by p455w0rd** [comment]
It should as I use a vanilla method to check for the key press which takes all OSes into account

**Comment by p455w0rd** [comment]
At any rate I posted a gif of this functionality  (pick block) in action on my Twitter  (@TheRealp455w0rd)
