### ISSUE TITLE
Sorting/Locking Request

### ISSUE THREAD

**Issue by TookUrSweetRoll** [p455w0rd/DankNull#89]
In issue #43 you said you hadn't ruled out the idea of sorting and/or locking the position of blocks. Did you decide either way?

My main reason is OCD. Not going to lie :)  The argument for keeping an eye on the count is valid, except when builders wands are involved.  Filling a hole with cobblestone or misclicking and flattening out the desert (happened yesterday) are two examples.

**Comment by p455w0rd** [comment]
This is now resolved by setting each item's "Placement Mode" and leaving at least 1 of said item/block
