### ISSUE TITLE
Dank Null Pulls Armor Off

### ISSUE THREAD

**Issue by blichte1** [p455w0rd/DankNull#93]
Using Dank Null in Lost Souls results in armor getting removed when attempting to shift items over from the primary inventory. No actual items are placed into dank null, and for perhaps obvious reasons the dank null does not extract items as designed...

**Comment by blichte1** [comment]
Ah! The bug only appears if you reassign the key binding for opening the dank null.

**Comment by p455w0rd** [comment]
yeah..this was a desync..fixed in dev (will be in next update)..thanks for posting :)
