### ISSUE TITLE
potions bug

### ISSUE THREAD

**Issue by coldblacksnow** [p455w0rd/DankNull#95]
when you try put different potions, while holding "shift" and pressing LMB, all different potions become one(first potion you store in)
![2018-03-10_18 37 02](https://user-images.githubusercontent.com/34198111/37244548-64c2634c-2493-11e8-80fc-1c43b0644cdb.png)
![2018-03-10_18 37 09](https://user-images.githubusercontent.com/34198111/37244550-689fbcbc-2493-11e8-8f9e-21d1de754296.png)
![2018-03-10_18 37 20](https://user-images.githubusercontent.com/34198111/37244551-6bec50c4-2493-11e8-8502-bedba695eed6.png)

**Comment by coldblacksnow** [comment]
even without holding 'shift' - same result

**Comment by p455w0rd** [comment]
looking into this now

**Comment by gorimare64** [comment]
Converts Blood Magic's Demonic Wills into the first added to the Dank Null (upgrades/downgrades will values). Presumably do to not matching meta or nbt values.

**Comment by ProsperCraft** [comment]
I don't understand, how is this not fixed six months later?

I just had all of the Thaumcraft crystals I mined for the last three hours turned into one type... I am now the owner of 505 Aer crystals, and none others, rip my evening.

**Comment by ProsperCraft** [comment]
Someone just pointed out that I can use the bug in reverse once I have one of each type to balance them out...will do that for now.

**Comment by ProsperCraft** [comment]
You can dupe the amazing enchants you have on one Adventurerers toolbox tool on to another tool of the same durability, this is bad.

**Comment by p455w0rd** [comment]
remove the mod and stop flooding my repo please..I have responded...I have been working on it...I'm not Jesus..sorry
