### ISSUE TITLE
Quick item selection with middle click

### ISSUE THREAD

**Issue by n1b0r63** [p455w0rd/DankNull#97]
Hi,
Thank you for your awesome mod!
I have an idea that I think would greatly improve the item selection. When you have a lot of different items in your dank/null and you want to use them to build something, it can rapidly be a waste of time to scroll through all these to select the one you want, or to open the GUI to select it.
I think it would be really great if you could just select an item in the dank/null just by pressing a button while targeting the same item in the world. Doing that you could just easily swap between different type of blocks while building.
If I remember correctly, usually in other mods to select an item in the world (like for example building wands or resonant exchanger) you shift+right click the item. But in the dank/null it open the GUI. So maybe the middle click, or eventually shift+middle click ?
I don't know if it's difficult to make, but I really think that it would make that awesome tool even more awesome :)

**Comment by n1b0r63** [comment]
Sorry, didn't saw it was already requested ^^

**Comment by p455w0rd** [comment]
lol..yup..and already implemented in dev..just reworking the packet handling..and it's taking forever to get everything working..but it's getting there
