### ISSUE TITLE
Can't add/remove items from /dank/null

### ISSUE THREAD

**Issue by kenshin13850** [p455w0rd/DankNull#98]
Running FTB Revelations 1.6.0 on MC 1.12 (latest build). Whenever I take an item out of my /dank/null and put it in my inventory (say to craft something), as soon as I click anywhere it disappears from my inventory and returns to the /dank/null. In order to get stuff out, I have to throw it on the ground directly from the /dank/null interface, then drop the /dank/null, and pick the item up again. I also can't add new items to the /dank/null. They just return to my inventory. It feels like the inventory of the /dank/null is locked. 

I can still add items that are already in the /dank/null to it.

**Comment by kenshin13850** [comment]
I have found that this only occurs when using the "open nearest danknull" key that I assigned in options. It does not happen if I shift-click to open it.

**Comment by dmsaxon** [comment]
Agree - only seems to malfunction (in a variety of ways, including items going missing, pulling armour and/or items from other slots) if you use the 'open nearest' function.
