### ISSUE TITLE
Crash upon logging into server

### ISSUE THREAD

**Issue by Lithorn** [p455w0rd/DankNull#99]
https://pastebin.com/VS6B8ht4

Seem to be crashing now upon logging into our server. Unsure if its the dank nulls in my inventory (They dont have all slots filled and are not full, are blue level or green (Cant remember)), or if we've got one placed causing the issue. It references a render crash with the dank null

**Comment by p455w0rd** [comment]
yup..this is same as #92 unfortunately, the update isn't ready..hang tight..it'll get there
